### ISSUE TITLE
Issue running Price

### ISSUE THREAD

**Issue by TamaraO** [erhard-lab/gedi#1]
Hello, 

When I try to run gedi price on the sample dataset, the script starts running successfully, but gets quickly stuck and just hangs there without progressing. This is the log: 

```
login03:~/Ribo-seq/Price$ more gedi.e1501242
2018-03-13 16:15:10.601 INFO Command: gedi -e Price -reads hsv_8.cit -genomic homo_sapiens.75 -prefix testone -progress
2018-03-13 16:15:11.584 INFO Discovering classes in classpath
2018-03-13 16:15:11.925 INFO Preparing simple class references
2018-03-13 16:15:12.340 INFO Gedi 1.0.1 (JAR) startup
2018-03-13 16:15:12.907 INFO Reading oml /home/unix/tamarao/.gedi/genomic/homo_sapiens.75.oml
2018-03-13 16:15:13.015 INFO Done reading oml /home/unix/tamarao/.gedi/genomic/homo_sapiens.75.oml
2018-03-13 16:15:16.740 INFO Estimating maxpos...
2018-03-13 16:15:16.749 INFO Clustering reads
Processed 187116 elements in 9s 110ms (Throughput: 20537.4/sec)
| Collecting statistics 8+:17447194-17447222                   16152 (1855.3/sec)
2018-03-13 16:15:26.025 SEVERE Exception in PriceIdentifyMaxPos0(0):[{0:Boolean},{1:Boolean},{2:Boolean},{3:Boolean}]->[{4:Boolean}] (id=2bbfc7df):java.lang.Runt
imeException: Could not run gedi.riboseq.javapipeline.PriceIdentifyMaxPos@2eed8db2
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:64)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:28)
	at gedi.util.job.FireTransition.call(FireTransition.java:55)
	at gedi.util.job.FireTransition.call(FireTransition.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Concurrency problem!
	at gedi.core.region.feature.GenomicRegionFeatureProgram$Runner.shutdown(GenomicRegionFeatureProgram.java:242)
	at gedi.core.region.feature.GenomicRegionFeatureProgram.end(GenomicRegionFeatureProgram.java:348)
	at gedi.core.region.feature.AlignedReadsDataToFeatureProgram.processStorage(AlignedReadsDataToFeatureProgram.java:170)
	at gedi.riboseq.javapipeline.PriceIdentifyMaxPos.execute(PriceIdentifyMaxPos.java:87)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:62)
	... 7 more
Processed 187116 elements in 8s 402ms (Throughput: 22270.4/sec)
/ Collecting statistics 8+:21829425-21829453
/ Collecting
| Collecting statistics 8+:22447217-22447245                   339
| Collecting statistics 8+:2523789
|
\ Collecting statistics 8+:30402120-30402141|30416403-30
16412 57602 (4065.9/sec)2018-03-13 16:15:31.408 INFO Found 8648 clusters without looking at annotation
Processed 8648 elements in 1s 396ms (Throughput: 6194.8/sec)
- Collecting statistics 8+:59484868-59484873
- Colle
/ Collecting statistics 8+:97506516-97506547
/ Collecting s
| Collecting statistics 8+:144640
| Collecting statistics 8+:145218680-145218709                     181171 (8807.1/sec)2018-03-13 16:15:37.861 INFO Found 4027 clusters after looking at annotatio
n
- Collecting statistics 8+:145583311-145583342                     183847 (8851.1/sec)2018-03-13 16:15:38.003 INFO Found 532 clusters after filtering with read/r
egion count
Processed 187116 elements in 20s 972ms (Throughput: 8922.2/sec)
login03:~/Ribo-seq/Price$
```

This is the script I am submitting:

`/users/tamarao/Price_1.0.1/gedi -e Price -reads hsv_8.cit -genomic homo_sapiens.75 -prefix test_one -progress`

`gedi -e IndexGenome` worked successfully.

**Comment by florianerhard** [comment]
Dear TamaraO,

this appears to be a race condition in the parallel processing of read clusters... which is a bad thing, because I never encountered it and cannot reproduce it.

However, I think I spotted the problem. Could you fetch the current version from github by 

```
git clone git@github.com:erhard-lab/gedi.git
```

and then build it by
```
buildworkspace.bash <output-folder>
```

This builds everything using ant. Could you plz tell me whether this fixed this issue?

Best,
Florian

**Comment by bli25wisc** [comment]
@florianerhard , do you know how to set the number of threads used in the Pipeline? Thanks!

**Comment by TamaraO** [comment]
Hi Bo, 

Is it this: 

-nthreads <n>: Set the number of parallel threads to run PRICE (default: use all cores)
From https://github.com/erhard-lab/gedi/wiki/Price <https://github.com/erhard-lab/gedi/wiki/Price>

Tamara


--
Tamara Ouspenskaia
Post-doctoral Associate
Aviv Regev Group
Broad Institute of Harvard and MIT
415 Main Street
Cambridge, MA, 02142
(781) 354-2374 tamara.ru <http://tamara.ru/>@gmail.com

**Comment by bli25wisc** [comment]
Hi @florianerhard ,  I and Tamara are working together. 

After recompile the source codes, we can successfully finish the program. Thanks for your suggestions! 

However, PRICE reported the following errors:
[GediProgram-1-thread-20] ERROR smile.classification.LogisticRegression - Failed to train Logistic Regression on multi-core
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at smile.util.MulticoreExecutor.run(MulticoreExecutor.java:107)
        at smile.classification.LogisticRegression$BinaryObjectiveFunction.f(LogisticRegression.java:491)
        at smile.math.Math.min(Math.java:4978)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:258)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:200)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:187)
        at gedi.riboseq.inference.orf.StartCodonTraining$RangeAndStartClassifier.<init>(StartCodonTraining.java:184)
        at gedi.riboseq.inference.orf.StartCodonTraining.trainModel(StartCodonTraining.java:257)
        at gedi.riboseq.inference.orf.StartCodonTraining.train(StartCodonTraining.java:144)
        at gedi.riboseq.javapipeline.PriceStartPredictionTraining.execute(PriceStartPredictionTraining.java:107)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:62)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:28)
        at gedi.util.job.FireTransition.call(FireTransition.java:55)
        at gedi.util.job.FireTransition.call(FireTransition.java:26)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException

Because PRICE gives outputs, could you let us know if we can ignore this error message? If not, how could we fix it?

Thanks,
Bo

**Comment by florianerhard** [comment]
Dear Bo,

you should not ignore it, as this means that the training of the logistic regression model for start codon prediction failed. This would give you strange results on the start codons...

It is an error in the library (smile) we use for logistic regression and has again to to with parallel execution and I cannot reproduce it. If I may ask, on which hardware are you running PRICE?

As a workaround, could you try to deactivate parallel execution for smile (this wouldn't impact on the overall performance as this step is rather fast anyway)? You have to do the following steps:

1. Pull the current version from github: ``git pull`` in the gedi folder
2. Rebuild: ``buildworkspace.bash  <output-folder>``
3. Start gedi with the following parameter ``gedi -Dsmile.threads=1 -e Price ... ``

Another option would be to update the smile libraries in ``GediCore/lib/smile*`` (i.e. delete them and download the most [recent version](https://haifengl.github.io/smile/) )

I hope this helps. Since I cannot reproduce the error, I cannot test it myself!

Best regards,
Florian

**Comment by bli25wisc** [comment]
@florianerhard , if I want to replace smile*, do I need to put smile*-source.jar into GediCore/lib/?

**Comment by TamaraO** [comment]
@florianerhard Your suggestions have fixed the Error issues. The gedi -e Price now executes without errors. Thank you!
