### ISSUE TITLE
could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics

### ISSUE THREAD

**Issue by vladie0** [erhard-lab/gedi#10]
Dear Developer, 
I'm trying to implement a pipeline where GEDI PRICE is executed automatically through a python script.
Upon executing GEDI trough command line, i'm experiencing the following error:

2018-04-25 13:09:47.279 INFO Command: gedi -e Price -D -progress -fdr 0.1 -nthreads 1 -reads bamlist.bamlist -genomic homo_sapiens.91 -prefix test
2018-04-25 13:09:47.490 INFO Discovering classes in classpath
2018-04-25 13:09:47.518 INFO Preparing simple class references
2018-04-25 13:09:47.555 INFO Gedi 1.0.2 (JAR) startup
2018-04-25 13:09:48.606 INFO Reading oml /home/vladie/.gedi/genomic/homo_sapiens.91.oml
2018-04-25 13:09:48.619 INFO Done reading oml /home/vladie/.gedi/genomic/homo_sapiens.91.oml
2018-04-25 13:09:52.686 INFO Estimating maxpos...
2018-04-25 13:09:52.726 INFO Clustering reads
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@130636cb
Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@130636cb

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files

java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@130636cb
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:222)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:68)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@130636cb
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at gedi.riboseq.cleavage.CleavageModelEstimator.setMerge(CleavageModelEstimator.java:132)
        at gedi.riboseq.javapipeline.PriceCollectSufficientStatistics.execute(PriceCollectSufficientStatistics.java:58)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more

Anyway to solve this issue ? 
Kind Regards,
Vladie0

**Comment by vladie0** [comment]
Dear Florianerhard,

This was indeed the issue, I managed to fix this.
However, in the meantime I've encountered a new issue. This issue occurs when attempting to process C.elegans RIBO-seq data. The genome was downloaded and indexed as described in your tutorial (no errors).

Running Price on the data provides the following error:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by gedi.util.orm.ClassTree (file:/data/Price_1.0.2/gedi.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of gedi.util.orm.ClassTree
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-05-04 13:09:12.066 INFO Considering 12240 ORFs for start training
[GediProgram-1-thread-19] ERROR smile.classification.LogisticRegression - Failed to train Logistic Regression on multi-core
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 6000
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at smile.util.MulticoreExecutor.run(MulticoreExecutor.java:107)
        at smile.classification.LogisticRegression$BinaryObjectiveFunction.f(LogisticRegression.java:491)
        at smile.math.Math.min(Math.java:4961)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:258)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:200)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:187)
        at gedi.riboseq.inference.orf.StartCodonTraining$RangeAndStartClassifier.<init>(StartCodonTraining.java:175)
        at gedi.riboseq.inference.orf.StartCodonTraining.trainModel(StartCodonTraining.java:256)
        at gedi.riboseq.inference.orf.StartCodonTraining.train(StartCodonTraining.java:143)
        at gedi.riboseq.javapipeline.PriceStartPredictionTraining.execute(PriceStartPredictionTraining.java:106)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6000
        at smile.classification.LogisticRegression$BinaryObjectiveFunction$GTask.call(LogisticRegression.java:463)
        at smile.classification.LogisticRegression$BinaryObjectiveFunction$GTask.call(LogisticRegression.java:436)
        ... 4 more
[GediProgram-1-thread-19] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-19] ERROR smile.classification.LogisticRegression - Failed to train Logistic Regression on multi-core
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 6000
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at smile.util.MulticoreExecutor.run(MulticoreExecutor.java:107)
        at smile.classification.LogisticRegression$BinaryObjectiveFunction.f(LogisticRegression.java:403)
        at smile.math.Math.linesearch(Math.java:4814)
        at smile.math.Math.min(Math.java:4976)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:258)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:200)
        at smile.classification.LogisticRegression.<init>(LogisticRegression.java:187)
        at gedi.riboseq.inference.orf.StartCodonTraining$RangeAndStartClassifier.<init>(StartCodonTraining.java:175)
        at gedi.riboseq.inference.orf.StartCodonTraining.trainModel(StartCodonTraining.java:256)
        at gedi.riboseq.inference.orf.StartCodonTraining.train(StartCodonTraining.java:143)
        at gedi.riboseq.javapipeline.PriceStartPredictionTraining.execute(PriceStartPredictionTraining.java:106)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6000
        at smile.classification.LogisticRegression$BinaryObjectiveFunction$FTask.call(LogisticRegression.java:384)
        at smile.classification.LogisticRegression$BinaryObjectiveFunction$FTask.call(LogisticRegression.java:360)
        ... 4 more
[GediProgram-1-thread-19] ERROR smile.classification.LogisticRegression - Failed to train Logistic Regression on multi-core
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 6000

command used:
gedi -e Price -percond -nthreads 4 -reads bamlist.bamlist -genomic caenorhabditis_elegans.91 -fdr 0.1 -prefix cjtvblwyg

Any idea where the issue could reside ? 
Thank you in advance,
Vladie0

**Comment by florianerhard** [comment]
Dear Vladie0,

could you please open another issue for a different error?

Some users experience this error, which has to do with the smile library that is used for logistic regression. Please delete the outputs and restart with `gedi  -Dsmile.threads=1 -e Price...`

Best regards,
Florian
