### ISSUE TITLE
gedi -e FastqFilter -D -overwrite -ld mESC.nos4U.C.readlengths.tsv -min 18 mESC.nos4U.C.fastq This script doesn't work.

### ISSUE THREAD

**Issue by Lilycream** [erhard-lab/gedi#10]
An error occurred: Could not connect to R!

**Comment by Lilycream** [comment]
Dear Prof.Erhard:
Thanks for your reply, here is the error message:
gedi -t . -e FastqFilter -D -overwrite -ld mESC.nos4U.C.readlengths.tsv $EQUAL_LEN -min 18 mESC.nos4U.C.fastq
2024-06-27 21:39:30.957 INFO OS: Linux 6.5.0-41-generic amd64
2024-06-27 21:39:30.988 INFO Java: OpenJDK 64-Bit Server VM 11.0.13+7-b1751.21
2024-06-27 21:39:31.033 INFO Discovering classes in classpath
2024-06-27 21:39:31.203 INFO Preparing simple class references
2024-06-27 21:39:31.274 INFO Gedi version 1.0.6a (JAR) startup
2024-06-27 21:39:31.275 INFO Command: gedi -e FastqFilter -D -overwrite -ld mESC.nos4U.C.readlengths.tsv -min 18 mESC.nos4U.C.fastq
2024-06-27 21:39:40.057 INFO Processed 23522518 reads!
2024-06-27 21:39:40.407 SEVERE Failed running Rserve!
java.lang.RuntimeException: R returned error code 1
	at gedi.util.r.RConnect.<init>(RConnect.java:53)
	at gedi.util.r.RConnect.getInstance(RConnect.java:25)
	at gedi.util.r.RConnect.R(RConnect.java:40)
	at gedi.util.plotting.GGPlot.prepareR(GGPlot.java:84)
	at gedi.util.plotting.GGPlot.png(GGPlot.java:67)
	at executables.FastqFilter.start(FastqFilter.java:375)
	at executables.FastqFilter.main(FastqFilter.java:38)

An error occurred: Could not connect to R!
java.lang.RuntimeException: Could not connect to R!
	at gedi.util.r.RConnect.<init>(RConnect.java:72)
	at gedi.util.r.RConnect.getInstance(RConnect.java:25)
	at gedi.util.r.RConnect.R(RConnect.java:40)
	at gedi.util.plotting.GGPlot.prepareR(GGPlot.java:84)
	at gedi.util.plotting.GGPlot.png(GGPlot.java:67)
	at executables.FastqFilter.start(FastqFilter.java:375)
	at executables.FastqFilter.main(FastqFilter.java:38)
Caused by: java.lang.RuntimeException: R returned error code 1
	at gedi.util.r.RConnect.<init>(RConnect.java:53)
	... 6 more
2024-06-27 21:39:40.409 INFO Finished: gedi -e FastqFilter -D -overwrite -ld mESC.nos4U.C.readlengths.tsv -min 18 mESC.nos4U.C.fastq

I created a bioinfo environment in conda and ran gedi in it. I reinstalled R, Java, and Maven in this environment and reinstalled gedi, but it seems that it still doesn't work properly, and it still prompts that Rserve cannot be correctly invoked.
Best,
Lilycream
