### ISSUE TITLE
Could not run gedi.riboseq.javapipeline.PriceClusterReads@4264356b

### ISSUE THREAD

**Issue by sarazaccara** [erhard-lab/gedi#16]
Hi Florian,

I'm trying to run Price on a .bam file (homo_sapiens.75) aligned using STAR.  I prepared the genome according to your pipeline using the IndexGenome program (gedi -e IndexGenome -organism homo_sapiens -version 75 -p -nobowtie -nokallisto). 
I have the following error and I don't know how to continue. 
Can you help me out?

Thank you.
Sara

2018-08-01 08:23:15.761 INFO Command: gedi -e Price -reads nc1_rpfAligned.toTranscriptome.out.bam -genomic homo_sapiens.75 -prefix ./nc1_price_output/nc1_price -progress -plot
2018-08-01 08:23:16.069 INFO Discovering classes in classpath
2018-08-01 08:23:16.241 INFO Preparing simple class references
2018-08-01 08:23:16.385 INFO Gedi 1.0.2 (JAR) startup
2018-08-01 08:23:18.364 INFO Reading oml /home/sara/.gedi/genomic/homo_sapiens.75.oml
2018-08-01 08:23:18.374 INFO Done reading oml /home/sara/.gedi/genomic/homo_sapiens.75.oml
2018-08-01 08:23:20.170 INFO Estimating maxpos...
2018-08-01 08:23:20.181 INFO Clustering reads
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@4264356b
Could not run gedi.riboseq.javapipeline.PriceClusterReads@4264356b

**Comment by florianerhard** [comment]
Dear Sara,

could you delete the output files, and rerun with the `-D` parameter? This would give a more verbose error message. Also, the first few mappings in your bam file (`samtools view nc1_rpfAligned.toTranscriptome.out.bam | head`) would give a good impression on what your input data looks like!

Best,
Florian

**Comment by sarazaccara** [comment]
Dear Florian,

Thank you for your reply!
Hope this information will help: 
--------------------------------------------------------------------------------------------------
java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@569bf7f
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:222)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:68)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@569bf7f
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:196)
        at gedi.core.region.GenomicRegionStorage.iterateMutableReferenceGenomicRegions(GenomicRegionStorage.java:92)
        at gedi.core.region.GenomicRegionStorage.iterateReferenceGenomicRegions(GenomicRegionStorage.java:232)
        at gedi.riboseq.inference.clustering.RiboClusterBuilder.build(RiboClusterBuilder.java:135)
        at gedi.riboseq.javapipeline.PriceClusterReads.execute(PriceClusterReads.java:56)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more
--------------------------------------------------------------------------------------------------

This is how my .bam file looks like:
---------------------------------------------------------------------------------------------------
12408897_ACAAG_3        256     ENST00000588147 356     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:1
12408897_ACAAG_3        256     ENST00000592920 389     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:2
12408897_ACAAG_3        256     ENST00000589226 429     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:3
12408897_ACAAG_3        256     ENST00000593046 500     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:4
12408897_ACAAG_3        256     ENST00000587089 363     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:5
12408897_ACAAG_3        0       ENST00000585321 467     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:6
12408897_ACAAG_3        256     ENST00000587465 507     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:7
12408897_ACAAG_3        256     ENST00000593194 154     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:8
12408897_ACAAG_3        256     ENST00000588981 516     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:9
12408897_ACAAG_3        256     ENST00000536926 367     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:10
12408897_ACAAG_3        256     ENST00000291901 368     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:11
12408897_ACAAG_3        256     ENST00000356783 335     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:12
12408897_ACAAG_3        256     ENST00000587758 417     0       28M     *       0       0       AGCGGCGCCGGTCAGAGAGAGCCGAGCA    *       NH:i:13 HI:i:13
12408898_ATGAT_5        256     ENST00000498412 257     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:1
12408898_ATGAT_5        256     ENST00000441435 220     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:2
12408898_ATGAT_5        256     ENST00000409711 1943    0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:3
12408898_ATGAT_5        256     ENST00000456292 268     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:4
12408898_ATGAT_5        256     ENST00000419276 340     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:5
12408898_ATGAT_5        0       ENST00000409038 280     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:6
12408898_ATGAT_5        256     ENST00000409650 280     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:7
12408898_ATGAT_5        256     ENST00000409733 666     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:8
12408898_ATGAT_5        256     ENST00000409320 280     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:9
12408898_ATGAT_5        256     ENST00000409028 290     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:10
12408898_ATGAT_5        256     ENST00000264258 858     0       26M     *       0       0       TGCGGCTGTCCAGAAAACGTAATGAG      *       NH:i:11 HI:i:11
------------------------------------------------------------------------------------------------

Looking forward to figuring out where my mistake might be!
Thank you again.

Best,
Sara

**Comment by florianerhard** [comment]
Dear Sara,

you used STAR to map against a all mRNA sequences. PRICE does not support this (and I would advice against using STAR like this in any case). Instead, you should prepare a STAR index for the human genome (if you called IndexGenome like this, it has done this already for you in the subfolder `STAR-index`). Then you have to map your reads against this. Also do not forget to sort and index the bam file (see also the FAQ in the PRICE wiki)!

I hope this helped!
Best,
Florian
