### ISSUE TITLE
Additional GRAND-SLAM run failure with "Error: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@2cb4ef60 Could not run gedi.slam.javapipeline.SlamRates@2cb4ef60"

### ISSUE THREAD

**Issue by gval38** [erhard-lab/gedi#18]
Hello,

I am attempting to run GRAND-SLAM on bulk SLAM-seq data. I prepared the Gedi genome given only a .fa file and generated my mapped .cit file for input using Bam2CIT given a list of sample .bam files (also attempted with bamlist2cit given bamlist file).  I then attempt to run GRAND-SLAM as follows:

gedi -e Slam -genomic genome -prefix s4u/tc1 -plot -D -reads mapped.cit

However, it errors out with the message: "Error: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@2cb4ef60
Could not run gedi.slam.javapipeline.SlamRates@2cb4ef60"

I checked my lib subfolder (gedi>bin>lib) as recommended for this error, and I do have the nashorn-core-15.4.jar file. Error persists following GEDI reinstall. What do you recommend I do to help resolve this?

Full error message listed below, thanks:

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@2cb4ef60
Could not run gedi.slam.javapipeline.SlamRates@2cb4ef60

java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@2cb4ef60
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:222)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:403)
        at gedi.util.program.GediProgram.run(GediProgram.java:235)
        at executables.Slam.main(Slam.java:42)
Caused by: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@2cb4ef60
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:48)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:9)
        at gedi.util.job.FireTransition.call(FireTransition.java:37)
        at gedi.util.job.FireTransition.call(FireTransition.java:8)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at gedi.slam.javapipeline.SlamRates$RateDataset.getMismatchRate(SlamRates.java:555)
        at gedi.slam.javapipeline.SlamRates.lambda$execute$9(SlamRates.java:168)
        at gedi.slam.javapipeline.SlamRates.estimateOld(SlamRates.java:477)
        at gedi.slam.javapipeline.SlamRates.execute(SlamRates.java:168)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:45)
        ... 7 more

**Comment by aliuxt** [comment]
Hello, I have met the same problem, have you solved it?
