### ISSUE TITLE
PriceCollectSufficientStatistic error: Index 51 out of bounds for length 51

### ISSUE THREAD

**Issue by dougbarrows** [erhard-lab/gedi#19]
Hello!

I am trying to run the PRICE workflow on a bam file. I've indexed the genome used to do the alignment and I get the error below when running the following command: 'gedi -e Price -D -reads test_sorted.bam -genomic ensembl_mm10_rm_primary -prefix test_out'. 

I have also converted the bam file to a .cit file and I get the same error. Any thoughts you have would be greatly appreciated - thank you!

Std out:

2024-09-04 15:11:30.132 INFO OS: Linux 3.10.0-1127.el7.x86_64 amd64
2024-09-04 15:11:30.189 INFO Java: OpenJDK 64-Bit Server VM 11.0.23-internal+0-adhoc..src
2024-09-04 15:11:30.250 INFO Discovering classes in classpath
2024-09-04 15:11:30.432 INFO Preparing simple class references
2024-09-04 15:11:30.530 INFO Gedi version 1.0.6a (JAR) startup
2024-09-04 15:11:30.546 INFO Command: gedi -e Price -D -reads test_sorted.bam -genomic ensembl_mm10_rm_primary -prefix test_out
2024-09-04 15:11:30.546 INFO Price version 1.0.4
2024-09-04 15:11:30.718 INFO Reading oml /ru-auth/local/home/dbarrows/.gedi/genomic/ensembl_mm10_rm_primary.oml
2024-09-04 15:11:30.724 INFO Done reading oml /ru-auth/local/home/dbarrows/.gedi/genomic/ensembl_mm10_rm_primary.oml
2024-09-04 15:11:31.745 INFO Starting PriceIdentifyMaxPos ...
2024-09-04 15:11:31.745 INFO Starting PriceSetupOrfInference ...
2024-09-04 15:11:31.745 INFO Starting PriceClusterReads ...
2024-09-04 15:11:31.745 INFO Starting PriceCollectSufficientStatistics ...
2024-09-04 15:11:31.748 INFO Estimating maxpos...
2024-09-04 15:11:31.752 INFO Clustering reads
2024-09-04 15:11:32.165 INFO Finished PriceSetupOrfInference (time: 418ms)
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@3248c902
Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@3248c902
Index 51 out of bounds for length 51

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files
 -changelog            Show version changelog

java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@3248c902
	at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:222)
	at gedi.util.program.GediProgram$1.execute(GediProgram.java:403)
	at gedi.util.program.GediProgram.run(GediProgram.java:235)
	at executables.Price.main(Price.java:53)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@3248c902
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:48)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:9)
	at gedi.util.job.FireTransition.call(FireTransition.java:37)
	at gedi.util.job.FireTransition.call(FireTransition.java:8)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 51 out of bounds for length 51
	at gedi.riboseq.cleavage.CleavageModelEstimator.collectEstimateData(CleavageModelEstimator.java:367)
	at gedi.riboseq.javapipeline.PriceCollectSufficientStatistics.execute(PriceCollectSufficientStatistics.java:46)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:45)
	... 7 more
2024-09-04 15:11:33.816 INFO Finished: gedi -e Price -D -reads test_sorted.bam -genomic ensembl_mm10_rm_primary -prefix test_out

**Comment by punching-samuel** [comment]
Hi I have met the same error. If you already found the solution, could you please share with me.

Thank you!
Sammi

**Comment by dougbarrows** [comment]
Unfortunately I never found a solution and moved onto another software for this. Sorry!

**Comment by punching-samuel** [comment]
> Unfortunately I never found a solution and moved onto another software for this. Sorry!

Would you happen to have any software recommendations?

Thank you!
Sammi

**Comment by progistar** [comment]
Hi @dougbarrows @punching-samuel,
I just want to share my experience about that problem.
I solved the problem by realigning my fastq files with a few modifications of STAR aligner (simply remove --clip5pNbases):
 
* my original STAR option: --outSAMunmapped Within --outFilterMultimapNmax 10 --outFilterMismatchNmax 2 --outSAMattributes All --align EndsType EndToEnd --twoPassMode basci --quantMode TranscriptomeSAM --clip5pNbases 1

* my corrected STAR option: --outSAMunmapped Within --outFilterMultimapNmax 10 --outFilterMismatchNmax 2 --outSAMattributes All --align EndsType EndToEnd --twoPassMode basci --quantMode TranscriptomeSAM

I think the error seems to be related with soft-clip. You can try if you want to use PRICE!

**Comment by punching-samuel** [comment]
> Hi [@dougbarrows](https://github.com/dougbarrows) [@punching-samuel](https://github.com/punching-samuel), I just want to share my experience about that problem. I solved the problem by realigning my fastq files with a few modifications of STAR aligner (simply remove --clip5pNbases):
> 
> * my original STAR option: --outSAMunmapped Within --outFilterMultimapNmax 10 --outFilterMismatchNmax 2 --outSAMattributes All --align EndsType EndToEnd --twoPassMode basci --quantMode TranscriptomeSAM --clip5pNbases 1
> * my corrected STAR option: --outSAMunmapped Within --outFilterMultimapNmax 10 --outFilterMismatchNmax 2 --outSAMattributes All --align EndsType EndToEnd --twoPassMode basci --quantMode TranscriptomeSAM
> 
> I think the error seems to be related with soft-clip. You can try if you want to use PRICE!

Hi, may I ask how you performed the upstream processing of your Ribo-seq data?
In my workflow, I typically run adapter trimming with Trim Galore, followed by Bowtie alignment to check for rRNA and tRNA contamination.
However, I’m seeing a strange issue:
My own Ribo-seq dataset consistently triggers this error, but other publicly available Ribo-seq datasets do not.
Have you encountered something similar, or do you have any suggestions on what might be causing this?

**Comment by progistar** [comment]
> > Hi [@dougbarrows](https://github.com/dougbarrows) [@punching-samuel](https://github.com/punching-samuel), I just want to share my experience about that problem. I solved the problem by realigning my fastq files with a few modifications of STAR aligner (simply remove --clip5pNbases):
> > 
> > * my original STAR option: --outSAMunmapped Within --outFilterMultimapNmax 10 --outFilterMismatchNmax 2 --outSAMattributes All --align EndsType EndToEnd --twoPassMode basci --quantMode TranscriptomeSAM --clip5pNbases 1
> > * my corrected STAR option: --outSAMunmapped Within --outFilterMultimapNmax 10 --outFilterMismatchNmax 2 --outSAMattributes All --align EndsType EndToEnd --twoPassMode basci --quantMode TranscriptomeSAM
> > 
> > I think the error seems to be related with soft-clip. You can try if you want to use PRICE!
> 
> Hi, may I ask how you performed the upstream processing of your Ribo-seq data? In my workflow, I typically run adapter trimming with Trim Galore, followed by Bowtie alignment to check for rRNA and tRNA contamination. However, I’m seeing a strange issue: My own Ribo-seq dataset consistently triggers this error, but other publicly available Ribo-seq datasets do not. Have you encountered something similar, or do you have any suggestions on what might be causing this?

I processed the data using nf-core rna-seq pipeline (https://nf-co.re/rnaseq/3.21.0). This pipeline uses TrimGalore for trimming adapter and SortMeRNA for filtering out RNA contamination. The beauty of the pipeline is that it provides whole-package and automatic processing. I recommend trying this pipeline for your dataset (it works for ribo-seq dataset).
