### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: javafx/beans/property/ObjectProperty

### ISSUE THREAD

**Issue by VirginieR** [erhard-lab/gedi#24]
Dear Florian, 

I am trying to execute GEDI PRICE in order to get the ORFs from Ribo seq data.
Unfortunately, I am experiencing the following error:

`[ruizma@arion Price_1.0.3]$ /u/ruizma/Price_1.0.3/gedi -e Price -D -novelTranscripts -reads /home/Aligned.sortedByCoord.out.bam -genomic homo_ens88 -prefix price/hsv -progress -plot
2019-04-15 09:16:22.353 INFO Command: gedi -e Price -D -novelTranscripts -reads /home/Aligned.sortedByCoord.out.bam -genomic homo_ens88 -prefix price/hsv -progress -plot
2019-04-15 09:16:22.472 INFO Discovering classes in classpath
2019-04-15 09:16:22.520 INFO Preparing simple class references
2019-04-15 09:16:22.592 INFO Gedi 1.0.2 (JAR) startup
2019-04-15 09:16:22.669 SEVERE Could not load startup FxStartup.class in /u/ruizma/Price_1.0.3/gedi.jar
2019-04-15 09:16:22.761 INFO Reading oml /u/ruizma/.gedi/genomic/homo_ens88.oml
2019-04-15 09:16:22.765 INFO Done reading oml /u/ruizma/.gedi/genomic/homo_ens88.oml
2019-04-15 09:16:23.476 INFO Estimating maxpos...
2019-04-15 09:16:23.482 INFO Clustering reads
Processed 6249000 elements in 21m 31s 322ms (Throughput: 4839.2/sec)
\ Identify maxpos 5983953 (4633.8/sec)
\ Clustering reads 6225178 (4190.5/sec)
- Identify maxpos 6252074 (4208.7/sec)PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.NoClassDefFoundError: javafx/beans/property/ObjectProperty
javafx/beans/property/ObjectProperty
javafx.beans.property.ObjectProperty

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files

java.lang.RuntimeException: java.lang.NoClassDefFoundError: javafx/beans/property/ObjectProperty
	at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
	at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
	at gedi.util.program.GediProgram.run(GediProgram.java:204)
	at executables.Price.main(Price.java:69)
Caused by: java.lang.NoClassDefFoundError: javafx/beans/property/ObjectProperty
	at gedi.util.io.text.tsv.formats.Csv.toDataFrame(Csv.java:44)
	at gedi.riboseq.javapipeline.PriceEstimateModel.execute(PriceEstimateModel.java:74)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
	at gedi.util.job.FireTransition.call(FireTransition.java:54)
	at gedi.util.job.FireTransition.call(FireTransition.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javafx.beans.property.ObjectProperty
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
2019-04-15 09:41:09.101 INFO Finished: gedi -e Price -D -novelTranscripts -reads /home/Aligned.sortedByCoord.out.bam -genomic homo_ens88 -prefix price/hsv -progress -plot`

Do you know how I can solve this issue?
Thank you in advance,

Virginie

**Comment by VirginieR** [comment]
I think I fixed. I didn't load the module of Java 1.8.  So, I did it and it seems working.
