### ISSUE TITLE
java.lang.IndexOutOfBoundsException: 1135502999 should be >=0 and <=1073741823 1135502999 should be >=0 and <=1073741823

### ISSUE THREAD

**Issue by VirginieR** [erhard-lab/gedi#26]
Dear Florian, 

I have been problems running Price.
I have the following error:

```
java.lang.IndexOutOfBoundsException: 1135502999 should be >=0 and <=1073741823
1135502999 should be >=0 and <=1073741823

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files

java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@35186941
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:69)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@35186941
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: 1135502999 should be >=0 and <=1073741823
        at gedi.centeredDiskIntervalTree.CenteredDiskIntervalTreeStorage.lambda$fill$1(CenteredDiskIntervalTreeStorage.java:446)
        at gedi.util.functions.MappedSpliterator.lambda$tryAdvance$0(MappedSpliterator.java:54)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
        at gedi.util.functions.MappedSpliterator.tryAdvance(MappedSpliterator.java:54)
        at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at gedi.centeredDiskIntervalTree.CenteredDiskIntervalTreeStorage.fill(CenteredDiskIntervalTreeStorage.java:436)
        at gedi.core.region.GenomicRegionStorage.fill(GenomicRegionStorage.java:202)
        at gedi.core.region.GenomicRegionStorage.fill(GenomicRegionStorage.java:187)
        at gedi.riboseq.inference.clustering.RiboClusterBuilder.build(RiboClusterBuilder.java:220)
        at gedi.riboseq.javapipeline.PriceClusterReads.execute(PriceClusterReads.java:56)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more
Caused by: java.lang.IndexOutOfBoundsException: 1135502999 should be >=0 and <=1073741823
        at gedi.util.io.randomaccess.BinaryWriter.putCInt(BinaryWriter.java:127)
        at gedi.riboseq.inference.clustering.RiboClusterInfo.serialize(RiboClusterInfo.java:63)
        at gedi.util.FileUtils.serialize(FileUtils.java:553)
        at gedi.centeredDiskIntervalTree.InternalCenteredDiskIntervalTreeBuilder.add(InternalCenteredDiskIntervalTreeBuilder.java:63)
        at gedi.centeredDiskIntervalTree.CenteredDiskIntervalTreeStorage.lambda$fill$1(CenteredDiskIntervalTreeStorage.java:440)
        ... 17 more`
```

I generated the bam file with STAR with the parameters specified in the PRICE wiki. Do you know what the problem might be?

Thanks in advance!

Virginie

**Comment by florianerhard** [comment]
Dear Virginie,
the technical reason: This number 1135502999 is the total number of reads in a single cluster that you got (multimappers counted multiple times). Price tries to write this into a binary file, but the number is too large for the (fixed-size) field in the binary file it is trying to write into. (That number is actually not even used further).

My guess why this is happening here is that STAR mapped a lot of (false) junction reads, tiling more or less a whole chromosome (i.e. there is one huge read cluster). In addition, there are many (probably very short) reads that all map at hundreds of locations.

As a solution, you can do two things:
1. Remove all reads shorter than 25(?) from the data (I thing --outFilterMatchNmin 25 for STAR)
2. Make STAR ignore splice junctions that are unknown (probably a good thing for ribo-seq; --alignIntronMax 1 for STAR)

Best,
Florian

**Comment by VirginieR** [comment]
Dear Florian, 

Thank you very much for your kind reply. 
I verified the length of the mapped reads and it is 26-34 ntds. 
I understand your suggestions and I will apply the first one. 
I had set --outFilterMatchNmin parameter to 23 but I will change it to 25.  Hopefully, this will make a difference.
On the other hand, I am not sure that I want to prohibit splicing. Do you have maybe any other suggestion?

Sincerely, 

Virginie
