### ISSUE TITLE
NullPointerException in SlamRates with GRAND-SLAM

### ISSUE THREAD

**Issue by aleighbrown** [erhard-lab/gedi#28]
Hi, 

We're trying to rerun some analysis with grand-slam and we keep getting a run time error. It gets through the finding snps phase and errors out at the estimate rate

command 
```
/tools/GRAND-SLAM_2.0.5c/gedi -e Slam -errlm TA*1.434 -genomic genecode_mouseMM22 -prefix grand_slam_analysis/test -progress -D -reads /data/STAR_aligned/test.Aligned.sorted.out.bam
```

error

```
Processed 55487 elements in 3m 43s 833ms (Throughput: 247.9/sec)
2019-09-04 17:50:50.555 INFO Auto-Detecting sequencing mode: Sense:3352546 Antisense:875647
2019-09-04 17:50:50.556 INFO Detected strand-specific sequencing (Sense)
2019-09-04 17:50:50.614 INFO Reading SNPs...
2019-09-04 17:50:50.954 INFO Read 36651 SNPs!
2019-09-04 17:50:50.956 INFO Collecting reads for each gene (Strand: Sense) ...
Processed 55487 elements in 101ms (Throughput: 549376.2/sec)
2019-09-04 17:50:51.533 INFO Writing statistics
2019-09-04 17:50:51.562 INFO Running R scripts for plotting
Error in `$<-.data.frame`(`*tmp*`, Mismatch, value = "->") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
2019-09-04 17:50:56.952 INFO Estimate conversions for old RNA using linear model TA*1.434 for mismatches on exons
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@415ad47e
Could not run gedi.slam.javapipeline.SlamRates@415ad47e

gedi -e Slam <Options>

General:
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
 -reads <reads>        The mapped reads from the SLAM-seq experiment.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@415ad47e
	at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
	at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
	at gedi.util.program.GediProgram.run(GediProgram.java:204)
	at executables.Slam.main(Slam.java:45)
Caused by: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@415ad47e
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
	at gedi.util.job.FireTransition.call(FireTransition.java:54)
	at gedi.util.job.FireTransition.call(FireTransition.java:25)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at gedi.slam.javapipeline.SlamRates$RateDataset.getMismatchRate(SlamRates.java:551)
	at gedi.slam.javapipeline.SlamRates.lambda$execute$7(SlamRates.java:179)
	at gedi.slam.javapipeline.SlamRates.estimateOld(SlamRates.java:473)
	at gedi.slam.javapipeline.SlamRates.execute(SlamRates.java:179)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
	... 7 more
```

**Comment by florianerhard** [comment]
Dear Anna-Leigh,
there is an error much earlier, 101ms for collecting all read data is way to fast. My guess is that something is wrong with the biotypes of your genes. In your prepared genome, is there a file `*.genes.tab`, which contains a `Biotype` column? Does it contain entries `protein_coding`?

By default, grand-slam only considers biotypes protein_coding, lincRNA and antisense (and all the IG_x and TR_x genes). 

You can also try to run `gedi -e Slam` with the `-allGenes` parameter!

Florian

**Comment by jon-xu** [comment]
Hi Florian,

I met the same problem and by checking the *.genes.tab you mentioned, the Biotype column contains all genes, but not "protein_coding", what's wrong do you recommend, please?

Thanks,
Jon

**Comment by florianerhard** [comment]
Dear Jon,
the Biotype column should contain biotypes (such as protein_coding), not genes. If this is empty, use the `-allGenes` parameter when calling GRAND-SLAM!
Best,
Florian

**Comment by jon-xu** [comment]
Thanks Florian! -allGenes works well!

Cheers,

Jon

**Comment by jon-xu** [comment]
Thanks Florian! -allGenes works well!

However, in the output ${prefix}.tsv I cannot find the below columns as described in the Wiki on Github:

XXX Conversions
The total number of conversions in this gene
XXX Coverage
The total number of U covered by any reads (if all U were converted, the Conversions=Coverage)
XXX Double-Hits
The same as Conversions, but only counting in doubly sequenced bases (paired-end)
XXX Double-Hit Coverage
The same as Coverage, but only counting in doubly sequenced bases (paired-end)
XXX min2
The number of reads with at least two characteristic mismatches

Could you please advise?

Jon

**Comment by aishwarya-gondane** [comment]
Hi Florian,

I am facing the same problem. I have tried using -allGenes, but the pipeline fails with the same error. Below is the error message. 

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@11b4e11b
Could not run gedi.slam.javapipeline.SlamRates@11b4e11b
Cannot invoke "javax.script.ScriptEngine.createBindings()" because "this.engine" is null

gedi -e Slam <Options>

General:
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
 -reads <reads>        The mapped reads from the SLAM-seq experiment.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@11b4e11b
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:375)
        at gedi.util.program.GediProgram.run(GediProgram.java:210)
        at executables.Slam.main(Slam.java:46)
Caused by: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@11b4e11b
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.createBindings()" because "this.engine" is null
        at gedi.util.nashorn.JS.<init>(JS.java:74)
        at gedi.slam.javapipeline.SlamRates.estimateOld(SlamRates.java:494)
        at gedi.slam.javapipeline.SlamRates.execute(SlamRates.java:192)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more
2024-01-31 08:22:07.365 INFO Finished: gedi -e Slam -genomic GRCh38_Gedi_index -plot -D -reads Control_NVP_scSLAM_mapped.cit -prefix Control_NVP_scSLAM_GrandSlam/GRAND_SLAM_240131 -allGenes -full -progress
2024-01-31 08:22:07.366 INFO Took 31m 0s 42ms
