### ISSUE TITLE
Unable to open Display

### ISSUE THREAD

**Issue by vladie0** [erhard-lab/gedi#3]
Dear developers, 

How can I use your software on a server where no Display is available ? (for server use)
Executing gedi command line generates the following error:

Exception in thread "FXlauncher" java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)

Thank you in advance,
Vladie

**Comment by florianerhard** [comment]
Dear Vladie,

I guess this is an error you get when you try to use the Config tool (``java -jar gedi.jar``). This is just a convenience tool and not necessary to run any of the programs. The important thing to do is to make the ``gedi`` script accessible via the PATH variable, as descrbibed in the [documentation](https://github.com/erhard-lab/gedi/wiki/Price#overview). Try: 

```
export PATH=$PATH:/home/erhard/Programs/PRICE_1.0.1
gedi -e Price -h
```

Best regards,
Florian

**Comment by vladie0** [comment]
Dear Florian, 

Thank you for your support. The problem with this approach is that I need to set the system variable java to oracle java, but I managed to circumvent the issue.

I have one more question which is not immediately clear to me.
I want to use your software package to detect sORF from BAM files, When I have both CHX & HARR BAM files (tranlating & initiating ribosome profile data). How exactly do I specify which treatment has been used, or doesn't it really matter for the software. In that case may I merge the BAM files ? 

Thank you for you support,
Vladie

**Comment by florianerhard** [comment]
Dear Vladie,

you do not have to specify that. For ORF identification, PRICE internally pools the reads of all specified mapping files. For finding the translation init site, a logistic regression model is learned, which should automatically recognize that the HRT sample is more important to find TISs. 

To specify more than one bam file when calling PRICE, use a [bamlist](https://github.com/erhard-lab/gedi/wiki/Price#using-price) file!

Best,
Florian

**Comment by vladie0** [comment]
Dear Florian, 

Thank you for clarifying! I've made several test runs which worked fine when a single BAM file was supplied. 

However when 2 bamfiles are provided (one for CHX and of for HARR data) I get the following error:
2018-03-21 16:51:11.555 INFO Command: gedi -e Price -reads test.bamlist -genomic homo_sapiens.91 -prefix crappe_2014 -nthreads 5 -progress -D
2018-03-21 16:51:11.796 INFO Discovering classes in classpath
2018-03-21 16:51:11.853 INFO Preparing simple class references
2018-03-21 16:51:11.912 INFO Gedi 1.0.2 (JAR) startup
2018-03-21 16:51:12.247 INFO Reading oml /home/vladie/.gedi/genomic/homo_sapiens.91.oml
2018-03-21 16:51:12.258 INFO Done reading oml /home/vladie/.gedi/genomic/homo_sapiens.91.oml
2018-03-21 16:51:15.652 INFO Estimating maxpos...
2018-03-21 16:51:15.665 INFO Clustering reads
Processed 7935565 elements in 10m 23s 381ms (Throughput: 12729.8/sec)
Processed 7935565 elements in 10m 45s 144ms (Throughput: 12300.5/sec)
/ Collecting statistics 20+:58891817-58891847                                     7280412 (11222.8/sec)2018-03-21 17:02:04.861 INFO Found 568041 clusters without looking at annotation
Processed 568041 elements in 5s 267ms (Throughput: 107849.1/sec)
| Collecting statistics 20-:54173953-54173982                                     7371990 (11237.4/sec)2018-03-21 17:02:12.119 INFO Found 287236 clusters after looking at annotation
/ Collecting statistics 21+:8209914-8209939|8437160-8437185                       7389885 (11235.4/sec)2018-03-21 17:02:13.845 INFO Found 41360 clusters after filtering with read/region count
Processed 7935565 elements in 16m 27s 800ms (Throughput: 8033.6/sec)
2018-03-21 17:07:46.013 INFO Using maxpos=12 (Merged)
2018-03-21 17:07:46.016 INFO Estimate parameters
Processed 99989870 elements in 22m 50s 14ms (Throughput: 72984.5/sec)
Correcting from 0 to 12 (desired: 12)
2018-03-21 17:30:36.137 INFO LL=-Infinity
2018-03-21 17:30:39.674 INFO Codon inference
- 1+:2189689-2189765 n=5 5/41360 (0.01%, 49.0/sec) Estimated time: 14:03PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCodonInference@4a5aee57
Could not run gedi.riboseq.javapipeline.PriceCodonInference@4a5aee57
Exception in parallel iterator thread!

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCodonInference@4a5aee57
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:222)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:68)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCodonInference@4a5aee57
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in parallel iterator thread!
        at gedi.util.functions.ParallelizedIterator.fatal(ParallelizedIterator.java:221)
        at gedi.util.functions.ParallelizedIterator.tryNext(ParallelizedIterator.java:189)
        at gedi.util.functions.ParallelizedIterator.hasNext(ParallelizedIterator.java:150)
        at gedi.riboseq.javapipeline.PriceCodonInference.execute(PriceCodonInference.java:106)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more
Caused by: java.lang.NullPointerException
        at gedi.riboseq.inference.codon.ReadsXCodonMatrix.computePriorReadProbabilities(ReadsXCodonMatrix.java:616)
        at gedi.riboseq.inference.codon.CodonInference.inferCodons(CodonInference.java:251)
        at gedi.riboseq.inference.codon.CodonInference.inferCodons(CodonInference.java:191)
        at gedi.riboseq.inference.codon.CodonInference.inferCodons(CodonInference.java:165)
        at gedi.riboseq.inference.orf.OrfInference.codonInference(OrfInference.java:261)
        at gedi.riboseq.javapipeline.PriceCodonInference.lambda$null$2(PriceCodonInference.java:101)
        at gedi.util.FunctorUtils$MappedIterator.next(FunctorUtils.java:1150)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:637)
        at gedi.util.FunctorUtils$FilteredIterator.lookAhead(FunctorUtils.java:1099)
        at gedi.util.FunctorUtils$FilteredIterator.hasNext(FunctorUtils.java:1088)
        at gedi.util.functions.ExtendedIterator.toCollection(ExtendedIterator.java:375)
        at gedi.util.functions.ParallelizedIterator$Worker.run(ParallelizedIterator.java:333)
2018-03-21 17:30:39.792 INFO Finished: gedi -e Price -reads test.bamlist -genomic homo_sapiens.91 -prefix crappe_2014 -nthreads 5 -progress -D

Is it possible to fix this issue ?

**Comment by florianerhard** [comment]
Dear Vladie,

hm, interesting. I recommend calling price with ``-percond `` (which will train a codon model for each bam file instead of a model for the pooled data, which probably makes more sense and will probably be the default in future releases).

I also tried to fix this bug (without being able to test it). So if you pull the newest version from github, you could also try it without ``-percond``.

Best,
Florian

**Comment by vladie0** [comment]
Dear Florian, 

The software seems to have processed the data without error using the -percond option.

Thank you for your support
