### ISSUE TITLE
GRAND-SLAM failed with the error "java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@78d34d4"

### ISSUE THREAD

**Issue by aishwarya-gondane** [erhard-lab/gedi#3]
I have two scSLAM-seq samples which I am trying to anayse first with GRAND-SLAM and then I plan to use it in GRANDR. However, my analysis failed with the below error
java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@78d34d4 

Can you please help me resolve this issue?

**Comment by danielrebib** [comment]
Sorry, could I ask how you downloaded this tool? The links in PRICE's tutorial for download do not work...

**Comment by florianerhard** [comment]
Can you please run gedi -e Slam... with the additional parameter -D and post the full error message?

@danielrebib  please don't crosspost!

**Comment by aishwarya-gondane** [comment]
Hi Florian,
I ran the command again with -D option, below is the error.

**Comment by florianerhard** [comment]
Gedi does not find the javascript engine. Is there a nashorn-core-15.4.jar file in the lib folder below `gedi`?

**Comment by aishwarya-gondane** [comment]
> This issue was fixed after reinstallation

I has installed this a long time ago and I don't remember if we need a license for it. But will try to do reinstall! 

Thanks,
Aish.

**Comment by Artur-man** [comment]
Dear all, 

I am having a similar issue, I am using `gedi -e Slam` I also imported manually the nashorn 15.6 lib under `GRAND-SLAM_2.0.7b/lib/` from `https://repo1.maven.org/maven2/org/openjdk/nashorn/nashorn-core/15.6/`. 

But here is the error: 

```
Picked up JAVA_TOOL_OPTIONS: -Xmx8g -Xss2560k
2025-06-04 09:12:03.744 INFO OS: Linux 5.14.0-427.13.1.el9_4.x86_64 amd64
2025-06-04 09:12:03.905 INFO Java: OpenJDK 64-Bit Server VM 21.0.2+-adhoc.nixbld.source
2025-06-04 09:12:03.957 WARNING Failed to read Jar file /fast/AG_Landthaler/scripts/GRAND-SLAM_2.0.7b/lib/._nashorn-core-15.6.jar
Exception in thread "main" java.lang.RuntimeException: Could not load JAR file ._nashorn-core-15.6.jar
	at gedi.app.classpath.JARClassPath.<init>(JARClassPath.java:69)
	at gedi.app.classpath.ClassPathFactory.createFromPaths(ClassPathFactory.java:72)
	at gedi.app.classpath.ClassPathFactory.createFromPath(ClassPathFactory.java:64)
	at gedi.app.classpath.ClassPathCache.<init>(ClassPathCache.java:62)
	at gedi.app.classpath.ClassPathCache.getInstance(ClassPathCache.java:52)
	at gedi.app.Gedi.getVersions(Gedi.java:115)
	at gedi.app.Gedi.version(Gedi.java:130)
	at gedi.app.Gedi.version(Gedi.java:137)
	at gedi.app.Gedi.startup(Gedi.java:61)
	at executables.Slam.main(Slam.java:47)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at gedi.app.classpath.JARClassPath.loadEntries(JARClassPath.java:76)
	at gedi.app.classpath.JARClassPath.<init>(JARClassPath.java:67)
```

Otherwise, I am getting the same `this.engine` error like above.
