### ISSUE TITLE
IndexGenome Error

### ISSUE THREAD

**Issue by KGillinder** [erhard-lab/gedi#34]
I am having trouble trying to prepare a genome index for hg19 (homo sapiens, UCSC) from the iGenomes (illumina) repository.

All input files are untouched, except the 'transcripts.gtf' which I have sorted by _transcriptID_ from the original 'genes.gtf' to avoid additional errors being thrown.

The command I am running is:

`gedi -e IndexGenome -a transcripts.gtf -s genome.fa -n hg19 -D`

The error thrown is as follows; with a lot of 'GenomicRegion not unique' lines removed as these appear to be a warning only, represented by '...':

>2019-09-27 11:06:05.839 INFO OS: Linux 3.10.0-957.5.1.el7.x86_64 amd64
2019-09-27 11:06:09.914 INFO Java: Java HotSpot(TM) 64-Bit Server VM 1.8.0_77-b03
2019-09-27 11:06:10.054 INFO Discovering classes in classpath
2019-09-27 11:06:10.186 INFO Preparing simple class references
2019-09-27 11:06:10.333 INFO Gedi version 1.0.2 (JAR) startup
2019-09-27 11:06:10.334 INFO Command: gedi -e IndexGenome -a transcripts.gtf -s genome.fa -n hg19 -D
Indexed fasta file in /references/GrandSlam/iGenomes/Homo_sapiens/UCSC/hg19/genome.fi
....
GenomicRegion not unique (for Transcript [geneId=OR4F29, transcriptId=NM_001005221_1, codingStart=621095, codingEnd=622034] and Transcript [geneId=OR4F3, transcriptId=NM_001005224, codingStart=621095, codingEnd=622034])
....
GeIndexed annotation file in transcripts.gtf.index
An error occurred: 0<0 or >=0
java.lang.IndexOutOfBoundsException: 0<0 or >=0
	at gedi.util.io.randomaccess.PageFile.getOffset(PageFile.java:462)
	at gedi.util.io.randomaccess.PageFile.get(PageFile.java:239)
	at gedi.util.io.randomaccess.PageFile.get(PageFile.java:248)
	at gedi.util.io.text.fasta.index.FastaIndexFile.create(FastaIndexFile.java:71)
	at gedi.util.io.text.fasta.index.FastaIndexFile.create(FastaIndexFile.java:57)
	at gedi.util.io.text.fasta.FastaFile.obtainAndOpenDefaultIndex(FastaFile.java:69)
	at executables.IndexGenome.start(IndexGenome.java:622)
	at executables.IndexGenome.main(IndexGenome.java:81)
2019-09-27 11:07:05.406 INFO Finished: gedi -e IndexGenome -a transcripts.gtf -s genome.fa -n hg19 -D
2019-09-27 11:07:05.407 INFO Took 59s 582ms

Any ideas? Happy to supply input files if required.

Thanks in advance.

**Comment by florianerhard** [comment]
Dear KGillinder,

could you please upload your gtf and tell me where I can download the genome.fa?

Florian

**Comment by KGillinder** [comment]
Hi Florian,

Thanks for your patience.

Here is the link for the [iGenomes hg19 build](http://igenomes.illumina.com.s3-website-us-east-1.amazonaws.com/Homo_sapiens/UCSC/hg19/Homo_sapiens_UCSC_hg19.tar.gz)

- genome.fa is found in `/Sequence/WholeGenomeFasta/genome.fa`
- gtf is a modified version of `/Annotation/Genes/genes.gtf` using the code below.

```
awk 'BEGIN{FS=";";}
     {
       for(i=1; i<=NF; i++)
       { match($i,/[[:space:]]*([[:print:]]+) "([[:print:]]+)"/,field);
         if (field[1] == "transcript_id")
         {
           tran=field[2];
         }
       }
       print tran,"\t",$0;
     }' genes.gtf | sort -k2,2 -k1,1 -k5,5n --buffer-size=1G | cut -f1 --complement > transcripts.gtf
```

Help is appreciated.

**Comment by KGillinder** [comment]
Any luck with this?

**Comment by florianerhard** [comment]
You have a space in front of all lines in the gtf you created!

A minimal example without having to download a 50GB archive would have been sufficient!

Florian

**Comment by KGillinder** [comment]
In hindsight your point is well made.

Thank you for your time in helping me solve this issue.

It is appreciated.
