### ISSUE TITLE
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamCollectStatistics@cf7356b

### ISSUE THREAD

**Issue by yangy1** [erhard-lab/gedi#36]
Hi Florian,

I encountered an error when I ran GRAND-SLAM and got empty results. My bam file (about 8G) was complete with the log pasted below:
Nov 22 15:23:50 ..... started STAR run
Nov 22 15:23:50 ..... loading genome
Nov 22 15:24:17 ..... processing annotations GTF
Nov 22 15:24:53 ..... inserting junctions into the genome indices
Nov 22 15:29:51 ..... started mapping
Nov 22 15:50:06 ..... finished mapping
Nov 22 15:50:06 ..... started sorting BAM
Nov 22 15:53:26 ..... finished successfully

Do you have some advice to solve my problem? Thank you very much!

The error was reported by GRAND-SLAM as below:

ESC[?25h^MESC[2K| In ENSG00000230025.1  57580/57781 (99.65%, 678.5/sec) Estimated time: 00:002019-11-23 10:03:08.617 INFO Auto
-Detecting sequencing mode: Sense:80865 Antisense:226494
2019-11-23 10:03:08.618 INFO Detected strand-specific sequencing (Antisense)
^MESC[2K/ In ENSG00000249634.1  57660/57781 (99.79%, 678.7/sec) Estimated time: 00:002019-11-23 10:03:08.636 INFO Reading SNPs
...
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamCollectStatistics@cf7356b
Could not run gedi.slam.javapipeline.SlamCollectStatistics@cf7356b
Could not read CSV file results/GRAND_results/5/5.snpdata
results/GRAND_results/5/5.snpdata: 不允许的操作 (Operation not permitted)

**Comment by yangy1** [comment]
when I looked for javapipeline in my env, I didn't find gedi/slam/javapipeline. Did I install the software successfully?

$ locate javapipeline
      1 /data/yyang/.gedi/build/src/gedi/lfc/localtest/javapipeline
      2 /data/yyang/.gedi/build/src/gedi/lfc/localtest/javapipeline/LTestParameterSet.java
      3 /data/yyang/.gedi/build/src/gedi/lfc/localtest/javapipeline/LTestRunner.java
      4 /data/yyang/.gedi/build/src/gedi/macoco/javapipeline
      5 /data/yyang/.gedi/build/src/gedi/macoco/javapipeline/CountEquivalenceClasses.java
      6 /data/yyang/.gedi/build/src/gedi/macoco/javapipeline/EquivalenceClassInfo.java
      7 /data/yyang/.gedi/build/src/gedi/macoco/javapipeline/EquivalenceClassesEffectiveLengths.java
      8 /data/yyang/.gedi/build/src/gedi/macoco/javapipeline/EquivalenceClassesMacoco.java
      9 /data/yyang/.gedi/build/src/gedi/macoco/javapipeline/EquivalenceClassesMaximumLikelihood.java
     10 /data/yyang/.gedi/build/src/gedi/macoco/javapipeline/EstimateTpm.java
     11 /data/yyang/.gedi/build/src/gedi/macoco/javapipeline/MacocoParameterSet.java
     12 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline
     13 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceClusterReads.java
     14 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceCodonInference.java
     15 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceCodonViewerIndices.java
     16 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceCollectSufficientStatistics.java
     17 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceDetermineDelta.java
     18 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceEstimateModel.java
     19 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceIdentifyMaxPos.java
     20 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceMultipleTestingCorrection.java
     21 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceNoiseTraining.java
     22 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceOptimisticCodonMapping.java
     23 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceOrfInference.java
     24 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceParameterSet.java
     25 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceReassignCodons.java
     26 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceSetupOrfInference.java
     27 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceSignalToNoise.java
     28 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceStartPredictionTraining.java
     29 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/PriceWriteCodons.java
     30 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/analyze
     31 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/analyze/PriceAnalyzeMajorIsoforms.java
     32 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/analyze/PriceIdentifyMajorIsoform.java
     33 /data/yyang/.gedi/build/src/gedi/riboseq/javapipeline/analyze/PriceLocalChanges.java
     34 /data/yyang/software/gedi/GediLFC/src/gedi/lfc/localtest/javapipeline
     35 /data/yyang/software/gedi/GediLFC/src/gedi/lfc/localtest/javapipeline/LTestParameterSet.java
     36 /data/yyang/software/gedi/GediLFC/src/gedi/lfc/localtest/javapipeline/LTestRunner.java
     37 /data/yyang/software/gedi/GediLFC/src/gedi/macoco/javapipeline
     38 /data/yyang/software/gedi/GediLFC/src/gedi/macoco/javapipeline/CountEquivalenceClasses.java
     39 /data/yyang/software/gedi/GediLFC/src/gedi/macoco/javapipeline/EquivalenceClassInfo.java
     40 /data/yyang/software/gedi/GediLFC/src/gedi/macoco/javapipeline/EquivalenceClassesEffectiveLeng
     40 ths.java
     41 /data/yyang/software/gedi/GediLFC/src/gedi/macoco/javapipeline/EquivalenceClassesMacoco.java
     42 /data/yyang/software/gedi/GediLFC/src/gedi/macoco/javapipeline/EquivalenceClassesMaximumLikeli
     42 hood.java
     43 /data/yyang/software/gedi/GediLFC/src/gedi/macoco/javapipeline/EstimateTpm.java
     44 /data/yyang/software/gedi/GediLFC/src/gedi/macoco/javapipeline/MacocoParameterSet.java
     45 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline
     46 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceClusterReads.java
     47 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceCodonInference.java
     48 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceCodonViewerIndices.java
     49 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceCollectSufficientStatistics.java
     50 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceDetermineDelta.java
     51 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceEstimateModel.java
     52 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceIdentifyMaxPos.java
     53 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceMultipleTestingCorrection.java
     54 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceNoiseTraining.java
     55 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceOptimisticCodonMapping.java
     56 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceOrfInference.java
     57 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceParameterSet.java
     58 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceReassignCodons.java
     59 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceSetupOrfInference.java
     60 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceSignalToNoise.java
     61 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceStartPredictionTraining.java
     62 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/PriceWriteCodons.java
     63 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/analyze
     64 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/analyze/PriceAnalyzeMajorIsoforms.java
     65 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/analyze/PriceIdentifyMajorIsoform.java
     66 /data/yyang/software/gedi/GediRiboSeq/src/gedi/riboseq/javapipeline/analyze/PriceLocalChanges.java


However,  there is no error when I print help
$ gedi -e Slam -h
2019-11-23 21:38:00.627 INFO OS: Linux 3.10.0-862.3.2.el7.x86_64 amd64
2019-11-23 21:38:00.654 INFO Java: OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
2019-11-23 21:38:00.758 INFO Discovering classes in classpath
2019-11-23 21:38:00.838 INFO Preparing simple class references
2019-11-23 21:38:00.912 INFO Gedi version 1.0.2 (JAR) startup
2019-11-23 21:38:00.912 INFO Command: gedi -e Slam -h
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

Usage:
gedi -e Slam <Options>

General:
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
 -reads <reads>        The mapped reads from the SLAM-seq experiment.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


2019-11-23 21:38:00.976 INFO Finished: gedi -e Slam -h
2019-11-23 21:38:00.977 INFO Took 356ms

**Comment by florianerhard** [comment]
Dear Yang,

your installation seems fine. Could you please post the full error log of grand-slam (you need to call it with `-D`)?

Florian

**Comment by yangy1** [comment]
OK.

$gedi -e Slam -genomic results/GRAND/index/hg19_gencode19.oml -prefix results/GRAND_results/test -D -reads results/starMap_results/5/out.bam -trim5p 0 -errlm TA*1.434

2019-11-24 15:23:21.543 INFO OS: Linux 3.10.0-862.3.2.el7.x86_64 amd64
2019-11-24 15:23:21.571 INFO Java: OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
2019-11-24 15:23:21.674 INFO Discovering classes in classpath
2019-11-24 15:23:21.753 INFO Preparing simple class references
2019-11-24 15:23:21.826 INFO Gedi version 1.0.2 (JAR) startup
2019-11-24 15:23:21.827 INFO Command: gedi -e Slam -genomic results/GRAND/index/hg19_gencode19.oml -prefix results/SLAMseq_IP_1st/GRAND_results/test -D -reads results/SLAMseq_IP_1st/starMap_results/5/out.bam -trim5p 0 -errlm TA*1.434
2019-11-24 15:23:21.909 INFO Reading oml results/GRAND/index/hg19_gencode19.oml
2019-11-24 15:23:21.916 INFO Done reading oml results/GRAND/index/hg19_gencode19.oml
2019-11-24 15:23:23.003 INFO Reading SNPs...
2019-11-24 15:23:23.036 INFO Read 18 SNPs!
2019-11-24 15:23:23.038 INFO Collecting reads for each gene (Strand: AutoDetect) ...
2019-11-24 15:23:24.063 INFO Writing statistics
2019-11-24 15:23:24.098 INFO Running R scripts for plotting
Rscript execution error: No such file or directory
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@20db5892
Could not run gedi.slam.javapipeline.SlamRates@20db5892
If you rerun, either delete the snps file or specify -strandness!

gedi -e Slam <Options>

General:
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
 -reads <reads>        The mapped reads from the SLAM-seq experiment.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@20db5892
	at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
	at gedi.util.program.GediProgram$1.execute(GediProgram.java:363)
	at gedi.util.program.GediProgram.run(GediProgram.java:208)
	at executables.Slam.main(Slam.java:45)
Caused by: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@20db5892
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
	at gedi.util.job.FireTransition.call(FireTransition.java:54)
	at gedi.util.job.FireTransition.call(FireTransition.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: If you rerun, either delete the snps file or specify -strandness!
	at gedi.slam.javapipeline.SlamRates.execute(SlamRates.java:127)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
	... 7 more
2019-11-24 15:23:24.129 INFO Finished: gedi -e Slam -genomic results/GRAND/index/hg19_gencode19.oml -prefix results/SLAMseq_IP_1st/GRAND_results/test -D -reads results/SLAMseq_IP_1st/starMap_results/5/out.bam -trim5p 0 -errlm TA*1.434
2019-11-24 15:23:24.130 INFO Took 2s 593ms

**Comment by yangy1** [comment]
OK. Thank you!

2019-11-24 15:36:13.844 INFO OS: Linux 3.10.0-862.3.2.el7.x86_64 amd64
2019-11-24 15:36:13.870 INFO Java: OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
2019-11-24 15:36:13.972 INFO Discovering classes in classpath
2019-11-24 15:36:14.049 INFO Preparing simple class references
2019-11-24 15:36:14.120 INFO Gedi version 1.0.2 (JAR) startup
2019-11-24 15:36:14.121 INFO Command: gedi -e Slam -genomic results/GRAND/index/hg19_gencode19.oml -prefix results/GRAND_results/5/5 -D -reads results/starMap_results/5/5_Aligned.sortedByCoord.out.bam -trim5p 0 -errlm TA*1.434
2019-11-24 15:36:14.202 INFO Reading oml results/GRAND/index/hg19_gencode19.oml
2019-11-24 15:36:14.209 INFO Done reading oml results/GRAND/index/hg19_gencode19.oml
2019-11-24 15:36:15.356 INFO Finding SNPs...
2019-11-24 15:42:33.273 INFO Auto-Detecting sequencing mode: Sense:152352 Antisense:687319
2019-11-24 15:42:33.275 INFO Detected strand-specific sequencing (Antisense)
2019-11-24 15:42:33.313 INFO Reading SNPs...
2019-11-24 15:42:33.551 INFO Read 36490 SNPs!
2019-11-24 15:42:33.552 INFO Collecting reads for each gene (Strand: Antisense) ...
2019-11-24 15:42:34.029 INFO Writing statistics
2019-11-24 15:42:34.058 INFO Running R scripts for plotting
Rscript execution error: No such file or directory
2019-11-24 15:42:34.113 INFO Estimate conversions for old RNA using linear model TA*1.434 for mismatches on exons
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@b5371aa
Could not run gedi.slam.javapipeline.SlamRates@b5371aa

gedi -e Slam <Options>

General:
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
 -reads <reads>        The mapped reads from the SLAM-seq experiment.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@b5371aa
	at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
	at gedi.util.program.GediProgram$1.execute(GediProgram.java:363)
	at gedi.util.program.GediProgram.run(GediProgram.java:208)
	at executables.Slam.main(Slam.java:45)
Caused by: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@b5371aa
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
	at gedi.util.job.FireTransition.call(FireTransition.java:54)
	at gedi.util.job.FireTransition.call(FireTransition.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at gedi.slam.javapipeline.SlamRates$RateDataset.getMismatchRate(SlamRates.java:553)
	at gedi.slam.javapipeline.SlamRates.lambda$execute$8(SlamRates.java:185)
	at gedi.slam.javapipeline.SlamRates.estimateOld(SlamRates.java:475)
	at gedi.slam.javapipeline.SlamRates.execute(SlamRates.java:185)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
	... 7 more
2019-11-24 15:42:34.743 INFO Finished: gedi -e Slam -genomic results/GRAND/index/hg19_gencode19.oml -prefix results/GRAND_results/5/5 -D -reads results/starMap_results/5/5_Aligned.sortedByCoord.out.bam -trim5p 0 -errlm TA*1.434
2019-11-24 15:42:34.746 INFO Took 6m 20s 907ms

**Comment by bsmalec** [comment]
I am encountering the same or very similar problem, has this issue been resolved @yangy1 @florianerhard ? Thanks!

My error message is below:

2020-03-19 16:02:02.926 INFO OS: Linux 3.10.0-327.3.1.el7.x86_64 amd64
2020-03-19 16:02:03.430 INFO Java: Java HotSpot(TM) 64-Bit Server VM 1.8.0_112-b15
2020-03-19 16:02:03.678 INFO Discovering classes in classpath
2020-03-19 16:02:03.830 INFO Preparing simple class references
2020-03-19 16:02:03.919 INFO Gedi version 1.0.2 (JAR) startup
2020-03-19 16:02:03.919 INFO Command: gedi -e Slam -genomic GCF_000001635.26_GRCm38.p6 -prefix 107_test2 -nthreads 2 -progress -plot -D -reads Aligned.out.sort.bam
2020-03-19 16:02:04.090 INFO Reading oml /home/bms36/.gedi/genomic/GCF_000001635.26_GRCm38.p6.oml
2020-03-19 16:02:04.104 INFO Done reading oml /home/bms36/.gedi/genomic/GCF_000001635.26_GRCm38.p6.oml
2020-03-19 16:02:05.951 INFO Finding SNPs...
...
Processed 42450 elements in 4m 26s 301ms (Throughput: 159.4/sec)
2020-03-19 16:06:33.103 INFO Auto-Detecting sequencing mode: Sense:813201 Antisense:113199
2020-03-19 16:06:33.104 INFO Detected strand-specific sequencing (Sense)
2020-03-19 16:06:33.127 INFO Reading SNPs...
2020-03-19 16:06:33.364 INFO Read 7172 SNPs!
2020-03-19 16:06:33.366 INFO Collecting reads for each gene (Strand: Sense) ...
Processed 42450 elements in 131ms (Throughput: 324045.8/sec)
2020-03-19 16:06:34.196 INFO Writing statistics
2020-03-19 16:06:34.283 INFO Running R scripts for plotting
Error in `$<-.data.frame`(`*tmp*`, Mismatch, value = "->") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
2020-03-19 16:06:35.617 INFO Estimate conversions for old RNA using linear model TA*1.434 for mismatches on exons
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamRates@4e63db77
Could not run gedi.slam.javapipeline.SlamRates@4e63db77

**Comment by bsmalec** [comment]
I just saw that my problem looks more like the one posted here: https://github.com/erhard-lab/gedi/issues/28 so I will check more upstream.

**Comment by jasperverwilt** [comment]
Has this error been resolved? The error encountered by @yangy1 seems different from the last one. I'm experiencing the same error:

2022-02-28 13:23:31.959 INFO OS: Linux 3.10.0-1160.49.1.el7.ug.x86_64 amd64
2022-02-28 13:23:32.098 INFO Java: OpenJDK 64-Bit Server VM 11.0.2+9
2022-02-28 13:23:32.126 INFO Discovering classes in classpath
2022-02-28 13:23:32.139 INFO Preparing simple class references
2022-02-28 13:23:32.176 INFO Gedi version 1.0.2 (JAR) startup
2022-02-28 13:23:32.367 INFO Command: gedi -e Slam -genomic rattus_norvegicus.104 -prefix grandslam_ratplasma/ -progress -D -reads ratplasma.bamlist -errlm TA*1.434 -allGenes
2022-02-28 13:23:32.368 INFO GRAND-SLAM version 2.0.5g-preview
2022-02-28 13:23:32.429 SEVERE Could not load startup FxStartup.class in GRAND_SLAMtest/gedi.jar
2022-02-28 13:23:32.543 INFO Reading oml /user/gent/424/vsc42458/.gedi/genomic/rattus_norvegicus.104.oml
2022-02-28 13:23:32.551 INFO Done reading oml /user/gent/424/vsc42458/.gedi/genomic/rattus_norvegicus.104.oml
2022-02-28 13:23:34.481 INFO Reading SNPs...
GrandSlam
Grand-Slam is an analysis method for SLAM/scSLAM-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamCollectStatistics@648bf54
Could not run gedi.slam.javapipeline.SlamCollectStatistics@648bf54

gedi -e GrandSlam <Options>

General:
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
 -reads <reads>        The mapped reads from the SLAM-seq experiment.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamCollectStatistics@648bf54
	at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
	at gedi.util.program.GediProgram$1.execute(GediProgram.java:375)
	at gedi.util.program.GediProgram.run(GediProgram.java:210)
	at executables.Slam.main(Slam.java:46)
Caused by: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamCollectStatistics@648bf54
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
	at gedi.util.job.FireTransition.call(FireTransition.java:54)
	at gedi.util.job.FireTransition.call(FireTransition.java:25)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at gedi.util.datastructure.collections.doublecollections.DoubleArrayList.add(DoubleArrayList.java:94)
	at gedi.util.datastructure.collections.doublecollections.DoubleArrayList.add(DoubleArrayList.java:30)
	at gedi.util.io.text.tsv.formats.CsvReader.lambda$readLists$9(CsvReader.java:206)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at gedi.util.io.text.tsv.formats.CsvReader.readLists(CsvReader.java:204)
	at gedi.util.io.text.tsv.formats.CsvReader.readDataFrame(CsvReader.java:142)
	at gedi.util.io.text.tsv.formats.Csv.toDataFrame(Csv.java:56)
	at gedi.util.io.text.tsv.formats.Csv.toDataFrame(Csv.java:36)
	at gedi.slam.javapipeline.SlamCollectStatistics.execute(SlamCollectStatistics.java:152)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
	... 7 more
2022-02-28 13:23:34.637 INFO Finished: gedi -e Slam -genomic rattus_norvegicus.104 -prefix grandslam_ratplasma/ -progress -D -reads ratplasma.bamlist -errlm TA*1.434 -allGenes
2022-02-28 13:23:34.639 INFO Took 5s 500ms
