### ISSUE TITLE
Issues during Read Clustering

### ISSUE THREAD

**Issue by HeyLifeHD** [erhard-lab/gedi#37]
Dear price authors,

I started working on ribo-seq data and wanted to run price on HISAT2 aligned bam files.
Therefore I created a cit file containing the alignments. When running price the following error occured:

/home/heyj/tools/Price_1.0.3/gedi -e Price \                                                                                                                                     > -reads /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/ribo.cit \                                                                                                                                        > -genomic /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr.oml \                                                                                                                        > -prefix /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr_analysis/price \                                                                                                              > -progress -plot -novelTranscripts                                                                                                                                                                       Picked up _JAVA_OPTIONS: -Dhttp://www-int2.inet.dkfz-heidelberg.de -Dhttp.proxyPort=80
2019-12-13 15:00:42.681 INFO Command: gedi -e Price -reads /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/ribo.cit -genomic /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr.oml -prefix /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr_analysis/price -progress -plot -novelTranscripts
2019-12-13 15:00:42.827 INFO Discovering classes in classpath
2019-12-13 15:00:42.959 INFO Preparing simple class references
2019-12-13 15:00:43.041 INFO Gedi 1.0.2 (JAR) startup
2019-12-13 15:00:43.197 INFO Reading oml /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr.oml
2019-12-13 15:00:43.203 INFO Done reading oml /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr.oml
2019-12-13 15:00:44.219 INFO Clustering reads
/ Clustering reads2019-12-13 15:00:44.278 INFO Using maxpos=11 (Merged)
2019-12-13 15:00:44.279 INFO Estimate parameters
Processed 9059654 elements in 55s 301ms (Throughput: 163821.5/sec)
| Model inference: Repeat 1139, Iteration 403: LL=-6.76627e+07; bestLL=-6.76625... 19085110 (316681.2/sec)2019-12-13 15:01:44.588 INFO Found 730820 clusters without looking at annotation
Processed 730820 elements in 7s 340ms (Throughput: 99566.8/sec)
| Model inference: Repeat 1402, Iteration 840: LL=-6.76790e+07; bestLL=-6.76625... 23537735 (319884.4/sec)2019-12-13 15:01:57.888 INFO Found 376933 clusters after looking at annotation
\ Model inference: Repeat 1485, Iteration 647: LL=-6.76786e+07; bestLL=-6.76625... 23902093 (320021.6/sec)2019-12-13 15:01:58.981 INFO Found 95231 clusters after filtering with read/region count
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@4206365b
Could not run gedi.riboseq.javapipeline.PriceClusterReads@4206365b
Comparison method violates its general contract!

I would be super grateful for support.

Best,

Joschka

**Comment by florianerhard** [comment]
Dear Joschka,

it seems that the read mappings are not properly ordered in the CIT file. Could you first try to run
```
gedi -e CorrectCIT /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/ribo.cit
```

then clear the Price output folder and rerun it?

If the error occurs again, please run price with the `-D` parameter and post the full error message!

Florian

**Comment by HeyLifeHD** [comment]
Dear Florian,

Thanks for your feedback. I have run the correctCIT script as well as clearing of the output folder. 
However, I still received the following error message:


/home/heyj/tools/Price_1.0.3/gedi -e Price -reads /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/ribo.cit -genomic /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr.oml -prefix /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr_analysis/price -progress -plot -novelTranscripts -D
Picked up _JAVA_OPTIONS: -Dhttp://www-int2.inet.dkfz-heidelberg.de -Dhttp.proxyPort=80
2019-12-16 10:34:01.129 INFO Command: gedi -e Price -reads /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/ribo.cit -genomic /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr.oml -prefix /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr_analysis/price -progress -plot -novelTranscripts -D
2019-12-16 10:34:01.284 INFO Discovering classes in classpath
2019-12-16 10:34:01.429 INFO Preparing simple class references
2019-12-16 10:34:01.520 INFO Gedi 1.0.2 (JAR) startup
2019-12-16 10:34:01.687 INFO Reading oml /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr.oml
2019-12-16 10:34:01.694 INFO Done reading oml /icgc/dkfzlsdf/analysis/C010/tinat/191212_Gedi/hg19_ensembl75_chr.oml
2019-12-16 10:34:02.678 INFO Estimating maxpos...
2019-12-16 10:34:02.682 INFO Clustering reads

Processed 9059654 elements in 17s 863ms (Throughput: 507145.9/sec)
Processed 9059654 elements in 24s 728ms (Throughput: 366372.3/sec)
| Collecting statistics 1-:155357779-155357810                     4279689 (157093.2/sec)2019-12-16 10:34:30.006 INFO Found 730820 clusters without looking at annotation
Processed 730820 elements in 3s 47ms (Throughput: 239849.0/sec)
| Collecting statistics 3+:101504365-101504394                     5020015 (159502.3/sec)2019-12-16 10:34:34.247 INFO Found 376933 clusters after looking at annotation
- Collecting statistics 3+:180325542-180325571                     5112187 (158886.9/sec)2019-12-16 10:34:34.888 INFO Found 95231 clusters after filtering with read/region count
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@7bc91a25
Could not run gedi.riboseq.javapipeline.PriceClusterReads@7bc91a25
Comparison method violates its general contract!

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@7bc91a25
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:69)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceClusterReads@7bc91a25
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866)
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483)
        at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
        at java.util.Arrays.sort(Arrays.java:1246)
        at gedi.core.region.GenomicRegionStorage.iterateMutableReferenceGenomicRegions(GenomicRegionStorage.java:94)
        at gedi.core.region.GenomicRegionStorage.getRandomRecord(GenomicRegionStorage.java:372)
        at gedi.centeredDiskIntervalTree.CenteredDiskIntervalTreeStorage.fill(CenteredDiskIntervalTreeStorage.java:396)
        at gedi.core.region.GenomicRegionStorage.fill(GenomicRegionStorage.java:202)
        at gedi.core.region.GenomicRegionStorage.fill(GenomicRegionStorage.java:187)
        at gedi.riboseq.inference.clustering.RiboClusterBuilder.build(RiboClusterBuilder.java:220)
        at gedi.riboseq.javapipeline.PriceClusterReads.execute(PriceClusterReads.java:56)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more

Thanks in advance.

Best,

Joschka

**Comment by florianerhard** [comment]
Dear Joschka,
it actually was not about the sorting of reads in the cit file, but about sorting of chromosome names. For some reason you have strange names in your cit file. To clarify that, you could run
```
gedi Nashorn -e 'print(load("ribo.cit").getReferenceSequences())'
``` 
and post the output here.

We fixed this issue, you can download the version 1.0.3a and retry!

Best,
Florian

**Comment by HeyLifeHD** [comment]
Thanks Florian for your feedback. I have been running Nashorn and got following output:

```
$ /home/heyj/tools/Price_1.0.3/gedi Nashorn -e 'print(load("ribo.cit").getReferenceSequences())'
2019-12-20 11:20:10.440 INFO Command: gedi Nashorn -e print(load("ribo.cit").getReferenceSequences())
2019-12-20 11:20:10.592 INFO Discovering classes in classpath
2019-12-20 11:20:10.728 INFO Preparing simple class references
2019-12-20 11:20:10.811 INFO Gedi 1.0.2 (JAR) startup
Exception in thread "main" java.lang.RuntimeException: Could not execute JS, dumb.js saved!
        at gedi.util.nashorn.JS.eval(JS.java:388)
        at Nashorn.main(Nashorn.java:47)
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot open ribo.cit. To create CIT, use the other constructor!
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at gedi.util.nashorn.JS.eval(JS.java:377)
        ... 1 more
Caused by: java.io.IOException: Cannot open ribo.cit. To create CIT, use the other constructor!
        at gedi.centeredDiskIntervalTree.CenteredDiskIntervalTreeStorage.<init>(CenteredDiskIntervalTreeStorage.java:126)
        at gedi.centeredDiskIntervalTree.CenteredDiskIntervalTreeStorageLoader.load(CenteredDiskIntervalTreeStorageLoader.java:39)
        at jdk.nashorn.internal.scripts.Script$Recompilation$6$20A$\^eval\_.load(<eval>:1)
        at jdk.nashorn.internal.scripts.Script$5$\^eval\_.:program(<eval>:1)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
```
I will run the update later today and let you know if it changed any of its previous behaviour. 

Best,

Joschka

**Comment by HeyLifeHD** [comment]
Hey Florian, I am not sure if I used the wrong download (wget https://github.com/erhard-lab/gedi/releases/download/Price_1.0.3a/Price_1.0.3a.tar.gz) but I cant find the gedi.jar file anymore. 
Sorry for all this inconvenience!
Best,
Joschka

**Comment by florianerhard** [comment]
Dear Joschka,

something went wrong during building the jar file. I fixed it and created a new release!
Florian

**Comment by HeyLifeHD** [comment]
Thanks, the download has worked this time!

**Comment by HeyLifeHD** [comment]
Also price seems to be running now. Thanks a lot.
