### ISSUE TITLE
Issue running pipeline

### ISSUE THREAD

**Issue by blackjack-uic** [erhard-lab/gedi#63]
Hi, thanks for the amazing work ! As I'm trying to implement PRICE pipeline into my work, there was an error that bugged me for a while. Thanks in advance if you guys could help take a look! While I was repeating what's shown in the example (hsv), something happened, here is the log:
```
2022-01-27 12:18:05.095 INFO Command: gedi -e Pipeline -r serial -j /mnt/f/ext_peptide/human_json.json shortread_mapping.sh resolve_ambi.sh report.sh price.sh
2022-01-27 12:18:05.307 INFO Discovering classes in classpath
2022-01-27 12:18:05.449 INFO Preparing simple class references
2022-01-27 12:18:05.606 INFO Gedi 1.0.2 (JAR) startup
2022-01-27 12:18:05.676 INFO Setting up runner
2022-01-27 12:18:05.678 INFO Reading json
2022-01-27 12:18:06.267 INFO Writing to /home/xshao/.gedi/genomic/./human_json/scripts/start.bash
2022-01-27 12:18:06.275 INFO Processing template shortread_mapping.sh
2022-01-27 12:18:07.539 INFO SRA entry: Name: hcmv.5hpi.cyc gsm: GSM1020234 id: 266560 SRR: [SRR609197]
An error occurred: Could not execute JS, dumb.js saved!
java.lang.RuntimeException: Could not execute JS, dumb.js saved!
        at gedi.util.nashorn.JS.eval(JS.java:369)
        at gedi.util.nashorn.JS.execSource(JS.java:343)
        at gedi.util.io.text.jhp.Jhp.apply(Jhp.java:142)
        at gedi.util.io.text.jhp.Jhp.apply(Jhp.java:98)
        at executables.Pipeline$PipelineFileProcessor.processTemplate(Pipeline.java:322)
        at executables.Pipeline$PipelineFileProcessor.include(Pipeline.java:303)
        at executables.Pipeline.start(Pipeline.java:254)
        at executables.Pipeline.main(Pipeline.java:50)
Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=sra&id=259475&rettype=docsum
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at gedi.util.nashorn.JS.eval(JS.java:356)
        ... 7 more
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=sra&id=259475&rettype=docsum
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1914)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at java.net.URL.openStream(URL.java:1092)
        at jdk.nashorn.internal.scripts.Script$29$\^eval\_.:program(<eval>:24)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        ... 13 more
2022-01-27 12:18:07.778 INFO Finished: gedi -e Pipeline -r serial -j /mnt/f/ext_peptide/human_json.json shortread_mapping.sh resolve_ambi.sh report.sh price.sh
```
and the human_json.json file looks like this:
```
{
"datasets": [
		{"gsm": "GSM1020234", "name": "hcmv.5hpi.cyc"},
		{"gsm": "GSM1020235", "name": "hcmv.24hpi.cyc"},
		{"gsm": "GSM1020236", "name": "hcmv.72hpi.cyc.A"},
		{"gsm": "GSM1020237", "name": "hcmv.72hpi.cyc.B"},
		{"gsm": "GSM1020238", "name": "hcmv.5hpi.harr"},
		{"gsm": "GSM1020239", "name": "hcmv.72hpi.harr"},
		{"gsm": "GSM1020240", "name": "hcmv.5hpi.ltm"},
		{"gsm": "GSM1020241", "name": "hcmv.72hpi.ltm"},
		{"gsm": "GSM1020242", "name": "hcmv.5hpi.non"},
		{"gsm": "GSM1020243", "name": "hcmv.72hpi.non"}
	],
"references": {"homo_sapiens.75": "both", "human_rrna": "rRNA"}
}
```
However, when I only applied PRICE on the mapped cit file it worked and generate the start.bash file as expected. Although when I tried to run the bash file, it seems like there is an out of memory issue occurred. The log is as follows:
```
xshao@DESKTOP-9OA4UCB:~/.gedi/genomic/human_json/scripts$ bash start.bash
2022-01-27 13:51:02.828 INFO Command: gedi -e Price -reads /mnt/f/ext_peptide/hsv_8.cit -genomic homo_sapiens.75 -prefix /home/xshao/.gedi/genomic/./human_json/price/human_json -plot -percond -D
2022-01-27 13:51:03.108 INFO Discovering classes in classpath
2022-01-27 13:51:03.245 INFO Preparing simple class references
2022-01-27 13:51:03.412 INFO Gedi 1.0.2 (JAR) startup
2022-01-27 13:51:03.674 INFO Reading oml /home/xshao/.gedi/genomic/homo_sapiens.75.oml
2022-01-27 13:51:03.683 INFO Done reading oml /home/xshao/.gedi/genomic/homo_sapiens.75.oml
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
GC overhead limit exceeded

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:69)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at gedi.riboseq.cleavage.RiboModel.deserialize(RiboModel.java:844)
        at gedi.riboseq.cleavage.RiboModel.fromFile(RiboModel.java:935)
        at gedi.riboseq.javapipeline.PriceCodonInference.execute(PriceCodonInference.java:75)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-01-27 14:28:19.956 INFO Command: gedi -e Stats -prefix /home/xshao/.gedi/genomic/./human_json/report/hsv_8. -g homo_sapiens.75 human_rrna /mnt/f/ext_peptide/hsv_8gedi -e Stats -prefix /home/xshao/.gedi/genomic/./human_json/report/hsv_8. -g homo_sapiens.75 human_rrna -count /mnt/f/ext_peptide/hsv_8
2022-01-27 14:28:20.413 INFO Discovering classes in classpath
2022-01-27 14:28:20.604 INFO Preparing simple class references
2022-01-27 14:28:20.844 INFO Gedi 1.0.2 (JAR) startup
An error occurred: No loader for /mnt/f/ext_peptide/hsv_8
```
Is there a way to resolve this? Thank you so much!
BTW, the java version I used is
```
$ java -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
```

**Comment by florianerhard** [comment]
Dear blackjack,
regarding the first problem: the http response code means "too many requests", and it occurs when the ncbi server is queried to map the GSMxxx ids to SRRxxx ids (that are necessary to download the fastq files). Have you only tried this once, or this this problem persist? We cannot reproduce this behavior here. A workaround would be to either manually hunt down the SRR ids for the given GEO ids and use "sra": "SRRxxx" instead of "gsm": "GSMxxx", or, to download the fastq files manually from SRA and using "fastq": "path/to/file" instead of "gsm": "GSMxxx".

regarding the second problem: The memory requirements for your file might indeed be higher than enabled by default. Try changing the gedi -e Price call in start.bash to `gedi -mem 32g -e Price ...`, or change the default in your gedi executable (`which gedi`) to `mem=32g`.

Best,
Florian

**Comment by blackjack-uic** [comment]
Hi Florian,

I managed to get it working by using version 1.0.3b instead of 1.0.3.

Thanks!
