### ISSUE TITLE
Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@d429ea3

### ISSUE THREAD

**Issue by A-X-Smitt** [erhard-lab/gedi#73]
Dear Florian,

while testing Gedi/Price I came across the following exit code:

```
Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@fccdfc1
Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@fccdfc1
-1
```

The extended error output:

```
java.lang.RuntimeException: java.lang.RuntimeException: 
 Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@d429ea3
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:239)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:416)
        at gedi.util.program.GediProgram.run(GediProgram.java:249)
        at executables.Price.main(Price.java:70)
Caused by: java.lang.RuntimeException: 
 Could not run gedi.riboseq.javapipeline.PriceCollectSufficientStatistics@d429ea3
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:65)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:26)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at gedi.riboseq.cleavage.CleavageModelEstimator.writeEstimateData(CleavageModelEstimator.java:441)
        at gedi.riboseq.javapipeline.PriceCollectSufficientStatistics.execute(PriceCollectSufficientStatistics.java:65)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:62)
        ... 7 more
```

The reference was built as documented for hg19. 
Any help is greatly appreciated! Thank you so much!

Alex

**Comment by florianerhard** [comment]
Dear Alex,
this error can only occur if not a single read is identified in your bam file. This can e.g. happen if the reference sequences in the bam file do not match to the chromosomes of your genome annotation. Did you map against the transcriptome as reference database (as you bam file name suggests)? I recommend mapping reads using STAR against the genome, and using these parameters (you might also want to set runThreadN and parameters for shared memory): 
```
STAR --runMode alignReads  --genomeDir $starindex --limitBAMsortRAM 8000000000 --alignIntronMax 1 --outFilterMismatchNmax 20 --outFilterScoreMinOverLread 0.25 --outFilterMatchNminOverLread 0.25 --readFilesIn $fastq --outSAMmode NoQS --outSAMtype BAM SortedByCoordinate --alignEndsType Extend5pOfReads12 --outSAMattributes nM MD NH
```
I hope this helps!
Best,
Florian

**Comment by A-X-Smitt** [comment]
Thank you, I will check it out and leave a comment.
