### ISSUE TITLE
Possible to manually set conversion and err rates for experiement?

### ISSUE THREAD

**Issue by aleighbrown** [erhard-lab/gedi#83]
Is there any way to directly specific a conversion and error rate? I'm using GRAND-SLAM_2.0.5c

e.g. I'm interested in manually entering the conversion and error rates
```
gedi -e Slam -conv 0.04919 -err 0.00050666 -reads my_aligned.bam -D -keep -genomic hdflf -prefix test_direct
```
Which gives the following output

```
2023-02-20 14:45:08.839 INFO Reading oml /home/annbrown/.gedi/genomic/hdflf.oml
2023-02-20 14:45:08.845 INFO Done reading oml /home/annbrown/.gedi/genomic/hdflf.oml
2023-02-20 14:45:08.987 INFO Finding SNPs...
2023-02-20 14:45:09.996 INFO Auto-Detecting sequencing mode: Sense:524 Antisense:46
2023-02-20 14:45:09.997 INFO Detected strand-specific sequencing (Sense)
2023-02-20 14:45:10.004 INFO Reading SNPs...
2023-02-20 14:45:10.029 INFO Read 0 SNPs!
2023-02-20 14:45:10.031 INFO Collecting reads for each gene (Strand: Sense) ...
2023-02-20 14:45:10.453 INFO Writing statistics
2023-02-20 14:45:10.687 INFO Running R scripts for plotting
Warning messages:
1: Removed 12 rows containing missing values (`geom_point()`). 
2: Removed 6 rows containing missing values (`geom_point()`). 
3: Removed 12 rows containing missing values (`geom_point()`). 
4: Removed 6 rows containing missing values (`geom_point()`). 
There were 18 warnings (use warnings() to see them)
null device 
          1 
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
null device 
          1 
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
null device 
          1 
null device 
          1 
2023-02-20 14:45:30.972 INFO Estimate conversions for old RNA using linear model TA*1.434 for mismatches on exons
2023-02-20 14:45:31.475 INFO Estimate conversions for new RNA using EM
2023-02-20 14:45:31.509 WARNING Too few reads (0) usable for estimating error and conversion rates; maybe your experiments did not work. To circumvent this warning, invoke with smaller -minEstimateReads or specify rates directly via -conv/-err!
2023-02-20 14:45:31.764 WARNING Could not compute new fraction!
2023-02-20 14:45:31.764 INFO For my_aligned: old=NaN new=0.9999999999995453 p in [0.0,1.0]
2023-02-20 14:45:31.791 INFO For my_aligned, conv_old=NaN conv_new=0.100
2023-02-20 14:45:31.891 INFO For my_aligned, using p_old = NaN  p_new=0.1 dp_old=1.0E-6 dp_new=1.0E-6
2023-02-20 14:45:31.892 INFO Infering old/new proportion...
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

```

if I look at the values in `test_direct.param` it looks like the conv and err values are being set, but Slam seems to still be trying to estimate rather than using the input values? 

```
snpConv	0.3
snppval	0.001
viral	null
allGenes	false
nUMI	false
mode	Weight
overlap	All
${prefix}.mismatches.tsv	null
${prefix}.doublehit.tsv	null
conv	0.04919
err	0.00050666
${prefix}.binom.tsv	null
${prefix}.overlap.tsv	null
plot	false
prefix	test_direct
minEstimateReads	10000
errlm	TA*1.434
errlm2	TA*1.434
${prefix}.binomOverlap.tsv	null
${prefix}.genedata	null
lower	0.05
upper	0.95
nthreads	20
genomic	hdflf
reads	TDPKD_2_8h.mdcalled
${prefix}.snpdata	null
locations	null
strandness	AutoDetect
trim5p	0
trim3p	0
${prefix}.rates.tsv	null
no4sUpattern	no4sU|nos4U
test	false
progress	false
D	true
h	false
hh	false
hhh	false
dry	false
keep	true
```

**Comment by florianerhard** [comment]
Strange, using -conv and -err should work as you intended. What is the content of the generated .rates file?

**Comment by aleighbrown** [comment]
```
Rate	my_aligned
single_old	NaN
single_new	0.1000
```

**Comment by aleighbrown** [comment]
More of the exact java errors in case that helps sus it out

```
2023-02-20 15:25:02.439 INFO Estimate conversions for old RNA using linear model TA*1.434 for mismatches on exons
2023-02-20 15:25:02.919 INFO Estimate conversions for new RNA using EM
2023-02-20 15:25:02.925 WARNING Too few reads (0) usable for estimating error and conversion rates; maybe your experiments did not work. To circumvent this warning, invoke with smaller -minEstimateReads or specify rates directly via -conv/-err!
2023-02-20 15:25:03.117 WARNING Could not compute new fraction!
2023-02-20 15:25:03.118 INFO For my_aligned.: old=NaN new=0.9999999999995453 p in [0.0,1.0]
2023-02-20 15:25:03.119 INFO For my_aligned., conv_old=NaN conv_new=0.100
2023-02-20 15:25:03.127 INFO For my_aligned., using p_old = NaN  p_new=0.1 dp_old=1.0E-6 dp_new=1.0E-6
2023-02-20 15:25:03.128 INFO Infering old/new proportion...
Slam
Slam is an analysis method for SLAM/scSLAM-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamInfer@3b5ddc4e
Could not run gedi.slam.javapipeline.SlamInfer@3b5ddc4e
Exception in parallel iterator thread!
illegal state: maximal count (10,000) exceeded: evaluations

gedi -e Slam <Options>

General:
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.
 -reads <reads>        The mapped reads from the SLAM-seq experiment.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamInfer@3b5ddc4e
	at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
	at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
	at gedi.util.program.GediProgram.run(GediProgram.java:204)
	at executables.Slam.main(Slam.java:45)
Caused by: java.lang.RuntimeException: Could not run gedi.slam.javapipeline.SlamInfer@3b5ddc4e
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
	at gedi.util.job.FireTransition.call(FireTransition.java:54)
	at gedi.util.job.FireTransition.call(FireTransition.java:25)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: Exception in parallel iterator thread!
	at gedi.util.functions.ParallelizedIterator.fatal(ParallelizedIterator.java:229)
	at gedi.util.functions.ParallelizedIterator.tryNext(ParallelizedIterator.java:197)
	at gedi.util.functions.ParallelizedIterator.hasNext(ParallelizedIterator.java:158)
	at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:640)
	at gedi.util.FunctorUtils$MappedIterator.hasNext(FunctorUtils.java:1191)
	at gedi.util.functions.ExtendedIterator.print(ExtendedIterator.java:483)
	at gedi.slam.javapipeline.SlamInfer.execute(SlamInfer.java:203)
	at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
	... 7 more
Caused by: org.apache.commons.math3.exception.TooManyEvaluationsException: illegal state: maximal count (10,000) exceeded: evaluations
	at org.apache.commons.math3.optim.BaseOptimizer$MaxEvalCallback.trigger(BaseOptimizer.java:242)
	at org.apache.commons.math3.util.Incrementor.incrementCount(Incrementor.java:155)
	at org.apache.commons.math3.optim.BaseOptimizer.incrementEvaluationCount(BaseOptimizer.java:191)
	at org.apache.commons.math3.optim.nonlinear.scalar.MultivariateOptimizer.computeObjectiveValue(MultivariateOptimizer.java:114)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.SimplexOptimizer$1.value(SimplexOptimizer.java:134)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.AbstractSimplex.evaluate(AbstractSimplex.java:250)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.NelderMeadSimplex.iterate(NelderMeadSimplex.java:277)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.SimplexOptimizer.doOptimize(SimplexOptimizer.java:172)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.SimplexOptimizer.doOptimize(SimplexOptimizer.java:88)
	at org.apache.commons.math3.optim.BaseOptimizer.optimize(BaseOptimizer.java:153)
	at org.apache.commons.math3.optim.BaseMultivariateOptimizer.optimize(BaseMultivariateOptimizer.java:65)
	at org.apache.commons.math3.optim.nonlinear.scalar.MultivariateOptimizer.optimize(MultivariateOptimizer.java:63)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.SimplexOptimizer.optimize(SimplexOptimizer.java:121)
	at gedi.slam.OptimNumericalIntegrationProportion.infer(OptimNumericalIntegrationProportion.java:229)
	at gedi.slam.javapipeline.SlamInfer.lambda$null$14(SlamInfer.java:169)
	at gedi.util.FunctorUtils$MappedIterator.next(FunctorUtils.java:1195)
	at gedi.util.functions.ExtendedIterator.toCollection(ExtendedIterator.java:445)
	at gedi.util.functions.ParallelizedIterator$Worker.run(ParallelizedIterator.java:341)
```

**Comment by florianerhard** [comment]
Could you please run:
```
gedi Nashorn -e "println(StringUtils.isNumeric('0.00050666'))"
```
and post the full output here?

The 'Estimate conversions for old RNA using linear model ' should not be done when specifying a numerical -err parameter (and for us, this does work)

**Comment by aleighbrown** [comment]
```
gedi Nashorn -e "println(StringUtils.isNumeric('0.00050666'))"
2023-02-20 16:17:50.670 INFO OS: Linux 3.10.0-1160.49.1.el7.x86_64 amd64
2023-02-20 16:17:50.815 INFO Java: Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
2023-02-20 16:17:50.847 INFO Discovering classes in classpath
2023-02-20 16:17:50.862 INFO Preparing simple class references
2023-02-20 16:17:50.907 INFO Gedi version 1.0.2 (JAR) startup
2023-02-20 16:17:50.908 INFO Command: gedi Nashorn -e println(StringUtils.isNumeric('0.00050666'))
true
2023-02-20 16:17:51.567 INFO Finished: gedi Nashorn -e println(StringUtils.isNumeric('0.00050666'))
2023-02-20 16:17:51.570 INFO Took 987ms
```

Also currently on this version of java

```
 java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

**Comment by florianerhard** [comment]
ok, this is as it is supposed to be. Could you please run Grand-Slam again (on a clean output dir), post the full command you used as well as the full output?

**Comment by aleighbrown** [comment]
```
ls
my_aligned.bam  my_aligned.bam.bai
(base) [annbrown@allen-606-4 new_clean_directory]$ gedi -e Slam -conv 0.04919 -err 0.00050666 -reads my_aligned.bam -D -keep -genomic hdflf -prefix test_direct

2023-02-20 16:38:45.374 INFO OS: Linux 3.10.0-1160.49.1.el7.x86_64 amd64
2023-02-20 16:38:46.006 INFO Java: OpenJDK 64-Bit Server VM 13.0.2+8
2023-02-20 16:38:46.070 INFO Discovering classes in classpath
2023-02-20 16:38:46.115 INFO Preparing simple class references
2023-02-20 16:38:46.204 INFO Gedi version 1.0.2 (JAR) startup
2023-02-20 16:38:46.206 INFO Command: gedi -e Slam -conv 0.04919 -err 0.00050666 -reads my_aligned.bam -D -keep -genomic hdflf -prefix test_direct
2023-02-20 16:38:46.303 SEVERE Could not load startup FxStartup.class in /SAN/vyplab/alb_projects/tools/GRAND-SLAM_2.0.5c/gedi.jar
2023-02-20 16:38:47.925 INFO Reading oml /home/annbrown/.gedi/genomic/hdflf.oml
2023-02-20 16:38:47.977 INFO Done reading oml /home/annbrown/.gedi/genomic/hdflf.oml
2023-02-20 16:38:52.299 INFO Finding SNPs...
2023-02-20 16:38:53.057 INFO Auto-Detecting sequencing mode: Sense:524 Antisense:46
2023-02-20 16:38:53.059 INFO Detected strand-specific sequencing (Sense)
2023-02-20 16:38:53.069 INFO Reading SNPs...
2023-02-20 16:38:53.147 INFO Read 0 SNPs!
2023-02-20 16:38:53.149 INFO Collecting reads for each gene (Strand: Sense) ...
2023-02-20 16:38:53.976 INFO Writing statistics
2023-02-20 16:38:54.382 INFO Running R scripts for plotting
Warning messages:
1: Removed 12 rows containing missing values (`geom_point()`). 
2: Removed 6 rows containing missing values (`geom_point()`). 
3: Removed 12 rows containing missing values (`geom_point()`). 
4: Removed 6 rows containing missing values (`geom_point()`). 
There were 18 warnings (use warnings() to see them)
null device 
          1 
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
null device 
          1 
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
null device 
          1 
null device 
          1 
2023-02-20 16:39:10.706 INFO Estimate conversions for old RNA using linear model TA*1.434 for mismatches on exons
Warning: Nashorn engine is planned to be removed from a future JDK release
2023-02-20 16:39:12.765 INFO Estimate conversions for new RNA using EM
2023-02-20 16:39:12.832 WARNING Too few reads (0) usable for estimating error and conversion rates; maybe your experiments did not work. To circumvent this warning, invoke with smaller -minEstimateReads or specify rates directly via -conv/-err!
2023-02-20 16:39:13.107 WARNING Could not compute new fraction!
2023-02-20 16:39:13.108 INFO For my_aligned: old=NaN new=0.9999999999995453 p in [0.0,1.0]
2023-02-20 16:39:13.128 INFO For my_aligned, conv_old=NaN conv_new=0.100
2023-02-20 16:39:13.172 INFO For my_aligned, using p_old = NaN  p_new=0.1 dp_old=1.0E-6 dp_new=1.0E-6
2023-02-20 16:39:13.172 INFO Infering old/new proportion...
2023-02-20 16:39:13.747 INFO Finished: gedi -e Slam -conv 0.04919 -err 0.00050666 -reads my_aligned.bam -D -keep -genomic hdflf -prefix test_direct
2023-02-20 16:39:13.749 INFO Took 28s 844ms
```

The GTF for building the index was a tiny part of the transcriptome (just a couple regions of a coupel genes), I was hoping to use the rates estimated by a full run to estimate some smaller fraction

happy to provide the GTF used to generate it

Output after running the above
```
-rw-r----- 1 annbrown vyp 4.9G Feb 20 16:33 my_aligned.bam
-rw-rw---- 1 annbrown vyp 6.8M Feb 20 16:38 my_aligned.bam.bai
-rw-rw---- 1 annbrown vyp  639 Feb 20 16:38 test_direct.param
-rw-rw---- 1 annbrown vyp   37 Feb 20 16:38 test_direct.snpdata
-rw-rw---- 1 annbrown vyp 1.1K Feb 20 16:38 test_direct.genedata
-rw-rw---- 1 annbrown vyp 1.8K Feb 20 16:38 test_direct.mismatches.tsv
-rw-rw---- 1 annbrown vyp 180K Feb 20 16:38 test_direct.mismatchdetails.tsv
-rw-rw---- 1 annbrown vyp   38 Feb 20 16:38 test_direct.binom.tsv
-rw-rw---- 1 annbrown vyp  412 Feb 20 16:38 test_direct.binomOverlap.tsv
-rw-rw---- 1 annbrown vyp   38 Feb 20 16:38 test_direct.overlap.tsv
-rw-rw---- 1 annbrown vyp  792 Feb 20 16:38 test_direct.doublehit.tsv
-rw-rw---- 1 annbrown vyp  31K Feb 20 16:39 test_direct.mismatches.pdf
-rw-rw---- 1 annbrown vyp  19K Feb 20 16:39 test_direct.mismatchpos.pdf
-rw-rw---- 1 annbrown vyp  19K Feb 20 16:39 test_direct.mismatchposzoomed.pdf
-rw-rw---- 1 annbrown vyp  22K Feb 20 16:39 test_direct.double.pdf
-rw-rw---- 1 annbrown vyp  117 Feb 20 16:39 test_direct.binomEstimated.tsv
-rw-rw---- 1 annbrown vyp   49 Feb 20 16:39 test_direct.rates.tsv
-rw-rw---- 1 annbrown vyp  267 Feb 20 16:39 test_direct.tsv
(base) [annbrown@allen-606-4 new_clean_directory]$ cat test_direct.rates.tsv 
Rate	my_aligned
single_old	NaN
single_new	0.1000
```

**Comment by florianerhard** [comment]
This problem is fixed in more up-to-date versions, please download the current version of GRAND-SLAM!\
Best,
Florian

**Comment by aleighbrown** [comment]
Your poor patent office people.  I'll register for the dowload link again - will update with result of the re-downloaded GRAND-SLAM. Which is the most recent version of GRAND-SLAM now?
